CREATE TABLE IF NOT EXISTS th_sessions (
    session_id    VARCHAR(100) UNIQUE NOT NULL,
    user_id       CHARACTER VARYING(100),
    user_name     CHARACTER VARYING(100),
    query_user_id VARCHAR(100),
    in_use        BOOLEAN DEFAULT TRUE,
    summary       TEXT,
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE th_sessions ADD COLUMN IF NOT EXISTS category     VARCHAR(50);
ALTER TABLE th_sessions ADD COLUMN IF NOT EXISTS preview      VARCHAR(200);  -- conversation preview snippet (matches test/prod)
ALTER TABLE th_sessions ADD COLUMN IF NOT EXISTS tags         JSONB;
ALTER TABLE th_sessions ADD COLUMN IF NOT EXISTS read_status  INTEGER DEFAULT 1;
ALTER TABLE th_sessions ADD COLUMN IF NOT EXISTS write_status INTEGER DEFAULT 1;
ALTER TABLE th_sessions ADD COLUMN IF NOT EXISTS ai_status    INTEGER DEFAULT 0;
ALTER TABLE th_sessions ADD COLUMN IF NOT EXISTS status       VARCHAR(10) DEFAULT 'active';
ALTER TABLE th_sessions ADD COLUMN IF NOT EXISTS language     VARCHAR(50);  -- AgentRequest.language hint; NULL/'' = auto-detect
ALTER TABLE th_sessions ADD COLUMN IF NOT EXISTS timezone     VARCHAR(64);  -- AgentRequest.timezone (IANA zone); NULL/'' = default
ALTER TABLE th_sessions ADD COLUMN IF NOT EXISTS files        TEXT;         -- JSON array of {name, key} attached this turn; NULL = none

CREATE INDEX IF NOT EXISTS idx_th_sessions_user_id  ON th_sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_th_sessions_tags     ON th_sessions USING GIN (tags);
CREATE INDEX IF NOT EXISTS idx_th_sessions_category ON th_sessions (category);

COMMENT ON COLUMN th_sessions.tags         IS 'Task-level tags generated by AI, stored as JSON array';
COMMENT ON COLUMN th_sessions.category     IS 'File category: food, report, medicine, rtc, journal, other';
COMMENT ON COLUMN th_sessions.write_status IS 'Write status: 0=edited (initial), 1=saved, 2=failed';
COMMENT ON COLUMN th_sessions.ai_status    IS 'AI processing status: 0=running, 1=succeeded, 2=failed';

------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS th_messages (
    id                VARCHAR(50)  UNIQUE NOT NULL,
    user_id           VARCHAR(100) NOT NULL,
    user_name         VARCHAR(100),
    session_id        VARCHAR(100) NOT NULL,
    role              VARCHAR(20)  NOT NULL,
    content           TEXT         NOT NULL,
    reasoning         TEXT,
    agent             VARCHAR(50),
    provider          VARCHAR(50),
    input_prompt      TEXT,
    question_id       VARCHAR(50),
    rating            INTEGER,
    created_at        TIMESTAMPTZ  DEFAULT CURRENT_TIMESTAMP,
    comment           TEXT,
    message_type      TEXT,
    is_del            BOOLEAN      NOT NULL DEFAULT FALSE,
    updated_at        TIMESTAMPTZ  DEFAULT CURRENT_TIMESTAMP,
    group_id          VARCHAR(64),
    scene             VARCHAR(32)  DEFAULT 'web',
    query_user_id     VARCHAR(100),
    reference_task_id VARCHAR(128) DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS idx_th_message_sessionID     ON th_messages (session_id);
CREATE INDEX IF NOT EXISTS idx_th_message_questionID    ON th_messages (question_id);
CREATE INDEX IF NOT EXISTS idx_th_messages_file_list    ON th_messages (user_id, message_type, is_del, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_th_messages_comment_trgm ON th_messages USING GIN (comment gin_trgm_ops);

------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS th_files (
    id                BIGSERIAL PRIMARY KEY,
    user_id           VARCHAR(50)  NOT NULL,
    query_user_id     VARCHAR(50),
    file_name         VARCHAR(255),
    file_type         VARCHAR(50),
    file_key          VARCHAR(255) NOT NULL,
    file_content      TEXT         NOT NULL DEFAULT '{}'::JSONB,  -- encrypted JSON metadata (encrypt_content); matches test/prod schema
    scene             VARCHAR(20),  -- food/report/medicine/journal/web/others ...
    created_source    VARCHAR(20)  NOT NULL,
    created_source_id VARCHAR(100),
    is_del            BOOLEAN      NOT NULL DEFAULT false,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

ALTER TABLE th_files ADD COLUMN IF NOT EXISTS original_text TEXT;
ALTER TABLE th_files ADD COLUMN IF NOT EXISTS text_length   INT DEFAULT 0;
ALTER TABLE th_files ADD COLUMN IF NOT EXISTS content_hash  VARCHAR(64);

CREATE INDEX IF NOT EXISTS idx_th_files_user_id           ON th_files (user_id);
CREATE INDEX IF NOT EXISTS idx_th_files_created_source    ON th_files (created_source);
CREATE INDEX IF NOT EXISTS idx_th_files_created_source_id ON th_files (created_source_id);
CREATE INDEX IF NOT EXISTS idx_th_files_created_at        ON th_files (created_at);
CREATE INDEX IF NOT EXISTS idx_th_files_content_hash      ON th_files (content_hash);

CREATE UNIQUE INDEX IF NOT EXISTS uq_th_files_file_key ON th_files (file_key);

COMMENT ON COLUMN th_files.content_hash IS 'SHA256 hash of file content, references th_file_contents table';
