// AUTO-DERIVED from htdoc/src/i18n.js -- the UI string table for the ten
// languages the app offers, kept verbatim so the Qt client and the web client
// read identically. `.pragma library` makes this a shared, stateless module.
// Regenerate by re-copying the STRINGS object from i18n.js if it changes.

.pragma library
var STRINGS = {
    en: {
        settings        : "Settings",
        language        : "Language",
        fontSize        : "Font size",
        fontSmaller     : "Smaller",
        fontSmall       : "Small",
        fontNormal      : "Normal",
        fontLarge       : "Large",
        fontLarger      : "Larger",
        backend         : "Backend",
        onDeviceAi      : "On-device AI",
        onDeviceIntro      : "Models run entirely on your device — offline and private. Add any GGUF here (download by URL, or point at a local file); pick which one to use from the model dropdown above the chat box.",
        modelReady         : "ready",
        modelDownloading   : "downloading",
        modelNotDownloaded : "not downloaded",
        modelFileMissing   : "file missing",
        download           : "Download",
        add                : "Add",
        deleteModel        : "Delete model",
        forgetModel        : "Forget (keeps your file)",
        deleteModelConfirm : "Delete “%s”? Its downloaded file will be removed from disk.",
        forgetModelConfirm : "Remove “%s” from the list? Your file on disk is kept.",
        modelName          : "Name",
        addLocalFile       : "Add local file…",
        manageModels       : "Manage on-device AI…",
        selectGgufModel    : "Select a GGUF model",
        suggested          : "Suggested",
        backendUrl      : "Backend URL",
        backendSubtitle : "Point this app at a Mirobody backend instance.",
        backendHint     : "Leave blank to use this server.",
        invalidUrl      : "Not a valid http(s) URL",
        save            : "Save",
        cancel          : "Cancel",
        signOut         : "Sign out",
        loginTitle      : "Sign in",
        loginSubtitle   : "We'll email you a one-time code.",
        authOr          : "or",
        continueWithGoogle : "Continue with Google",
        googleFailed    : "Google sign-in failed",
        continueWithWeChat : "Continue with WeChat",
        wechatFailed    : "WeChat sign-in failed",
        continueWithApple : "Continue with Apple",
        appleFailed     : "Apple sign-in failed",
        continueWithGitHub : "Continue with GitHub",
        githubFailed    : "GitHub sign-in failed",
        continueWithX   : "Continue with X",
        xFailed         : "X sign-in failed",
        sendCode        : "Send code",
        resendCode      : "Resend code",
        resendIn        : "Resend in %ss",
        verifyButton    : "Verify",
        selectModel     : "Select model",
        emptyTitle      : "Start a conversation",
        emptySubtitle   : "Pick a model below, then send your first message.",
        messageHint     : "Ask anything",
        send            : "Send",
        statsTitle      : "Response details",
        statsModel      : "Model",
        statsInput      : "Input tokens",
        statsOutput     : "Output tokens",
        statsTotalTokens : "Total tokens",
        statsTotalCost  : "Total cost",
        close           : "Close",
        copyReply       : "Copy reply",
        emailRequired   : "Email is required",
        sendingCode     : "Sending code…",
        codeSentTo      : "Code sent to %s.",
        sendFailed      : "Failed to send code.",
        enterCode       : "Enter the code from your email.",
        verifying       : "Verifying…",
        verifyFailed    : "Verification failed.",
        badResponse     : "Unexpected response from the server.",
        requestFailed   : "Something went wrong.",
        historyTitle    : "History",
        historyEmpty    : "No history yet.",
        historyUntitled : "Untitled",
        historyLoadFailed : "Failed to load history.",
        historyDeleteTitle : "Delete conversation?",
        historyDeleteMessage : "This conversation will be permanently removed.",
        delete          : "Delete",
        retry           : "Retry",
        back            : "Back",
        menuTitle       : "Menu",
        newChat         : "New chat",
        addAccount      : "Add account",
        incognitoMode   : "Incognito",
        incognitoStart  : "Turn on incognito",
        incognitoStop   : "Turn off incognito",
        incognitoHeading : "You're incognito",
        incognitoNote   : "Incognito chats aren't saved or added to memory.",
        signOutConfirm  : "Sign out of Mirobody?",
        sharedByBadge   : "Shared by %s",
        sharedWithBadge : "Shared with %s",
        healthData      : "Health & data",
        bluetoothDevices : "Bluetooth devices",
        bleTitle        : "Bluetooth health devices",
        bleIntro        : "Connect a standard Bluetooth LE sensor (heart-rate strap, blood-pressure cuff, thermometer). Readings are saved to your health record. Watches and rings use private protocols — connect those under vendors.",
        bleScan         : "Scan",
        bleScanning     : "Scanning…",
        bleStop         : "Stop",
        bleDisconnect   : "Disconnect",
        bleNoDevices    : "No devices yet — tap Scan",
        bleSupportedTag : "health",
        bleSaved        : "Saved %s reading(s)",
        bleFailedSuffix : ", %s failed",
        ehrConnect      : "Connect EHR",
        ehrConnectTitle : "Connect my EHR",
        ehrConnectSubtitle : "Search for a hospital or clinic, then sign in to share your records (SMART on FHIR).",
        ehrManualLabel  : "Or enter a FHIR base URL",
        ehrConnectBtn   : "Connect",
        ehrSearchPlaceholder : "Search providers (e.g. hospital name)",
        ehrSearch       : "Search",
        ehrSearching    : "Searching…",
        ehrNoResults    : "No matching providers.",
        ehrConnecting   : "Connecting…",
        ehrSyncNow      : "Sync now",
        ehrConnectedTitle : "EHR connected",
        ehrConnectedMsg : "Your EHR is connected. Sync now?",
        ehrSyncDoneTitle : "Sync complete",
        ehrSyncDoneMsg  : "Imported %s observations.",
        ehrErrorTitle   : "EHR error",
        ehrErrorMsg     : "Couldn't complete the request. Please try again.",
        ehrOk           : "OK",
        vendorManageTitle : "Connected devices",
        vendorManageSubtitle : "Connect or disconnect a device or service.",
        vendorNone      : "No connected devices yet.",
        vendorPending   : "Pending",
        vendorConnect   : "Connect",
        vendorGroupDevices : "Devices",
        vendorGroupPlatforms : "Platforms",
        vendorUnlink    : "Disconnect",
        vendorUnlinkTitle : "Disconnect device",
        vendorUnlinkMsg : "Disconnect %s?"
    },
    zh: {
        settings        : "设置",
        language        : "语言",
        fontSize        : "字号",
        fontSmaller     : "更小",
        fontSmall       : "小",
        fontNormal      : "正常",
        fontLarge       : "大",
        fontLarger      : "更大",
        backend         : "后端",
        onDeviceAi      : "本地 AI",
        onDeviceIntro      : "模型完全在你的设备上运行——离线且私密。在这里添加任意 GGUF(按 URL 下载,或指向本地文件);在聊天框上方的模型下拉框里选择使用哪个。",
        modelReady         : "已就绪",
        modelDownloading   : "下载中",
        modelNotDownloaded : "未下载",
        modelFileMissing   : "文件缺失",
        download           : "下载",
        add                : "添加",
        deleteModel        : "删除模型",
        forgetModel        : "移除(保留你的文件)",
        deleteModelConfirm : "删除“%s”?已下载的文件将从磁盘上移除。",
        forgetModelConfirm : "从列表中移除“%s”?磁盘上的文件会保留。",
        modelName          : "名称",
        addLocalFile       : "添加本地文件…",
        manageModels       : "管理本地模型…",
        selectGgufModel    : "选择 GGUF 模型",
        suggested          : "推荐",
        backendUrl      : "后端地址",
        backendSubtitle : "将此应用指向一个 Mirobody 后端实例。",
        backendHint     : "留空则使用当前服务器。",
        invalidUrl      : "不是有效的 http(s) URL",
        save            : "保存",
        cancel          : "取消",
        signOut         : "退出登录",
        loginTitle      : "登录",
        loginSubtitle   : "我们会通过邮件发送一次性验证码。",
        authOr          : "或",
        continueWithGoogle : "使用 Google 继续",
        googleFailed    : "Google 登录失败",
        continueWithWeChat : "使用微信继续",
        wechatFailed    : "微信登录失败",
        continueWithApple : "使用 Apple 继续",
        appleFailed     : "Apple 登录失败",
        continueWithGitHub : "使用 GitHub 继续",
        githubFailed    : "GitHub 登录失败",
        continueWithX   : "使用 X 继续",
        xFailed         : "X 登录失败",
        sendCode        : "发送验证码",
        resendCode      : "重新发送",
        resendIn        : "%s 秒后重新发送",
        verifyButton    : "验证",
        selectModel     : "选择模型",
        emptyTitle      : "开始对话",
        emptySubtitle   : "选择下方模型，然后发送第一条消息。",
        messageHint     : "有什么想问的？",
        send            : "发送",
        statsTitle      : "响应详情",
        statsModel      : "模型",
        statsInput      : "输入 Token",
        statsOutput     : "输出 Token",
        statsTotalTokens : "总 Token",
        statsTotalCost  : "总费用",
        close           : "关闭",
        copyReply       : "复制回复",
        emailRequired   : "请输入邮箱",
        sendingCode     : "正在发送验证码…",
        codeSentTo      : "验证码已发送至 %s。",
        sendFailed      : "发送验证码失败。",
        enterCode       : "请输入邮件中的验证码。",
        verifying       : "正在验证…",
        verifyFailed    : "验证失败。",
        badResponse     : "服务器返回的数据格式异常。",
        requestFailed   : "出错了，请稍后重试。",
        historyTitle    : "历史",
        historyEmpty    : "暂无历史记录。",
        historyUntitled : "未命名",
        historyLoadFailed : "加载历史记录失败。",
        historyDeleteTitle : "删除该会话？",
        historyDeleteMessage : "该会话将被永久删除。",
        delete          : "删除",
        retry           : "重试",
        back            : "返回",
        menuTitle       : "菜单",
        newChat         : "新对话",
        addAccount      : "添加账号",
        incognitoMode   : "隐私模式",
        incognitoStart  : "开启隐私模式",
        incognitoStop   : "关闭隐私模式",
        incognitoHeading : "已进入隐私模式",
        incognitoNote   : "隐私对话不会被保存，也不会写入记忆。",
        signOutConfirm  : "确定退出登录吗？",
        sharedByBadge   : "来自 %s 的分享",
        sharedWithBadge : "已分享给 %s 人",
        healthData      : "健康与数据",
        bluetoothDevices : "蓝牙设备",
        bleTitle        : "蓝牙健康设备",
        bleIntro        : "连接标准蓝牙 LE 传感器（心率带、血压袖带、体温计）。读数会保存到你的健康记录。手表和戒指使用私有协议——请在「已连接设备」中连接。",
        bleScan         : "扫描",
        bleScanning     : "扫描中…",
        bleStop         : "停止",
        bleDisconnect   : "断开",
        bleNoDevices    : "还没有设备——点击扫描",
        bleSupportedTag : "健康",
        bleSaved        : "已保存 %s 条读数",
        bleFailedSuffix : "，失败 %s 条",
        ehrConnect      : "连接病历（EHR）",
        ehrConnectTitle : "连接我的病历",
        ehrConnectSubtitle : "搜索医院或诊所，然后登录以共享你的病历（SMART on FHIR）。",
        ehrManualLabel  : "或输入 FHIR 基础地址",
        ehrConnectBtn   : "连接",
        ehrSearchPlaceholder : "搜索机构（如医院名称）",
        ehrSearch       : "搜索",
        ehrSearching    : "搜索中…",
        ehrNoResults    : "没有匹配的机构。",
        ehrConnecting   : "连接中…",
        ehrSyncNow      : "立即同步",
        ehrConnectedTitle : "已连接电子健康记录",
        ehrConnectedMsg : "我的电子健康记录已连接。现在同步数据吗？",
        ehrSyncDoneTitle : "同步完成",
        ehrSyncDoneMsg  : "已导入 %s 条观测数据。",
        ehrErrorTitle   : "EHR 错误",
        ehrErrorMsg     : "无法完成请求，请重试。",
        ehrOk           : "确定",
        vendorManageTitle : "已连接设备",
        vendorManageSubtitle : "连接或断开设备与服务。",
        vendorNone      : "尚无已连接的设备。",
        vendorPending   : "待验证",
        vendorConnect   : "连接",
        vendorGroupDevices : "设备",
        vendorGroupPlatforms : "平台",
        vendorUnlink    : "断开",
        vendorUnlinkTitle : "断开设备",
        vendorUnlinkMsg : "断开 %s？"
    },
    ja: {
        settings        : "設定",
        language        : "言語",
        fontSize        : "文字サイズ",
        fontSmaller     : "最小",
        fontSmall       : "小",
        fontNormal      : "標準",
        fontLarge       : "大",
        fontLarger      : "最大",
        backend         : "バックエンド",
        onDeviceAi      : "オンデバイス AI",
        onDeviceIntro      : "モデルは完全にデバイス上で動作します（オフライン・プライベート）。ここに任意の GGUF を追加し（URL からダウンロード、またはローカルファイルを指定）、チャット欄上部のドロップダウンで使用するモデルを選びます。",
        modelReady         : "準備完了",
        modelDownloading   : "ダウンロード中",
        modelNotDownloaded : "未ダウンロード",
        modelFileMissing   : "ファイルなし",
        download           : "ダウンロード",
        add                : "追加",
        deleteModel        : "モデルを削除",
        forgetModel        : "削除（ファイルは保持）",
        deleteModelConfirm : "「%s」を削除しますか?ダウンロード済みファイルはディスクから削除されます。",
        forgetModelConfirm : "「%s」を一覧から削除しますか?ディスク上のファイルは保持されます。",
        modelName          : "名前",
        addLocalFile       : "ローカルファイルを追加…",
        manageModels       : "オンデバイス AI を管理…",
        selectGgufModel    : "GGUF モデルを選択",
        suggested          : "おすすめ",
        backendUrl      : "バックエンド URL",
        backendSubtitle : "このアプリを Mirobody バックエンドのインスタンスに接続します。",
        backendHint     : "空欄の場合はこのサーバーを使用します。",
        invalidUrl      : "有効な http(s) URL ではありません",
        save            : "保存",
        cancel          : "キャンセル",
        signOut         : "ログアウト",
        loginTitle      : "ログイン",
        loginSubtitle   : "ワンタイムコードをメールで送信します。",
        authOr          : "または",
        continueWithGoogle : "Google で続行",
        googleFailed    : "Google サインインに失敗しました",
        continueWithWeChat : "WeChat で続行",
        wechatFailed    : "WeChat サインインに失敗しました",
        continueWithApple : "Apple で続行",
        appleFailed     : "Apple サインインに失敗しました",
        continueWithGitHub : "GitHub で続行",
        githubFailed    : "GitHub サインインに失敗しました",
        continueWithX   : "X で続行",
        xFailed         : "X サインインに失敗しました",
        sendCode        : "コードを送信",
        resendCode      : "コードを再送信",
        resendIn        : "%s 秒後に再送信",
        verifyButton    : "認証",
        selectModel     : "モデルを選択",
        emptyTitle      : "会話を始めましょう",
        emptySubtitle   : "下でモデルを選んで、最初のメッセージを送信してください。",
        messageHint     : "何でも質問してください",
        send            : "送信",
        statsTitle      : "応答の詳細",
        statsModel      : "モデル",
        statsInput      : "入力トークン",
        statsOutput     : "出力トークン",
        statsTotalTokens : "合計トークン",
        statsTotalCost  : "合計コスト",
        close           : "閉じる",
        copyReply       : "返信をコピー",
        emailRequired   : "メールアドレスを入力してください",
        sendingCode     : "コードを送信中…",
        codeSentTo      : "%s にコードを送信しました。",
        sendFailed      : "コードの送信に失敗しました。",
        enterCode       : "メールに記載のコードを入力してください。",
        verifying       : "認証中…",
        verifyFailed    : "認証に失敗しました。",
        badResponse     : "サーバーからの応答形式が予期しないものです。",
        requestFailed   : "エラーが発生しました。",
        historyTitle    : "履歴",
        historyEmpty    : "履歴はまだありません。",
        historyUntitled : "無題",
        historyLoadFailed : "履歴の読み込みに失敗しました。",
        historyDeleteTitle : "この会話を削除しますか？",
        historyDeleteMessage : "この会話は完全に削除されます。",
        delete          : "削除",
        retry           : "再試行",
        back            : "戻る",
        menuTitle       : "メニュー",
        newChat         : "新しいチャット",
        addAccount      : "アカウントを追加",
        incognitoMode   : "シークレット",
        incognitoStart  : "シークレットをオンにする",
        incognitoStop   : "シークレットをオフにする",
        incognitoHeading : "シークレット モードです",
        incognitoNote   : "シークレット チャットは保存されず、メモリにも追加されません。",
        signOutConfirm  : "ログアウトしますか？",
        sharedByBadge   : "%s からの共有",
        sharedWithBadge : "%s 人と共有中",
        healthData      : "健康とデータ",
        bluetoothDevices : "Bluetooth デバイス",
        bleTitle        : "Bluetooth 健康デバイス",
        bleIntro        : "標準的な Bluetooth LE センサー（心拍ベルト、血圧計、体温計）を接続します。測定値は健康記録に保存されます。時計や指輪は独自プロトコルのため、「接続済みデバイス」から接続してください。",
        bleScan         : "スキャン",
        bleScanning     : "スキャン中…",
        bleStop         : "停止",
        bleDisconnect   : "切断",
        bleNoDevices    : "デバイスがありません — スキャンをタップ",
        bleSupportedTag : "健康",
        bleSaved        : "%s 件を保存",
        bleFailedSuffix : "、失敗 %s 件",
        ehrConnect      : "EHR に接続",
        ehrConnectTitle : "自分の EHR に接続",
        ehrConnectSubtitle : "病院やクリニックを検索し、サインインして記録を共有します（SMART on FHIR）。",
        ehrManualLabel  : "または FHIR ベース URL を入力",
        ehrConnectBtn   : "接続",
        ehrSearchPlaceholder : "医療機関を検索（例：病院名）",
        ehrSearch       : "検索",
        ehrSearching    : "検索中…",
        ehrNoResults    : "一致する医療機関がありません。",
        ehrConnecting   : "接続中…",
        ehrSyncNow      : "今すぐ同期",
        ehrConnectedTitle : "EHR を連携しました",
        ehrConnectedMsg : "EHR が連携されました。今すぐデータを同期しますか？",
        ehrSyncDoneTitle : "同期完了",
        ehrSyncDoneMsg  : "%s 件の観測データを取り込みました。",
        ehrErrorTitle   : "EHR エラー",
        ehrErrorMsg     : "リクエストを完了できませんでした。もう一度お試しください。",
        ehrOk           : "OK",
        vendorManageTitle : "接続済みデバイス",
        vendorManageSubtitle : "デバイスやサービスを接続または切断します。",
        vendorNone      : "接続済みのデバイスはまだありません。",
        vendorPending   : "保留中",
        vendorConnect   : "接続",
        vendorGroupDevices : "デバイス",
        vendorGroupPlatforms : "プラットフォーム",
        vendorUnlink    : "切断",
        vendorUnlinkTitle : "デバイスを切断",
        vendorUnlinkMsg : "%s を切断しますか？"
    },
    ko: {
        settings        : "설정",
        language        : "언어",
        fontSize        : "글자 크기",
        fontSmaller     : "아주 작게",
        fontSmall       : "작게",
        fontNormal      : "보통",
        fontLarge       : "크게",
        fontLarger      : "아주 크게",
        backend         : "백엔드",
        onDeviceAi      : "온디바이스 AI",
        onDeviceIntro      : "모델은 전적으로 기기에서 실행됩니다 — 오프라인이며 비공개입니다. 여기에서 GGUF를 추가하고(URL로 다운로드하거나 로컬 파일 지정), 채팅창 위의 모델 드롭다운에서 사용할 모델을 선택하세요.",
        modelReady         : "준비됨",
        modelDownloading   : "다운로드 중",
        modelNotDownloaded : "다운로드 안 됨",
        modelFileMissing   : "파일 없음",
        download           : "다운로드",
        add                : "추가",
        deleteModel        : "모델 삭제",
        forgetModel        : "제거(파일 유지)",
        deleteModelConfirm : "“%s”을(를) 삭제할까요? 다운로드한 파일이 디스크에서 제거됩니다.",
        forgetModelConfirm : "목록에서 “%s”을(를) 제거할까요? 디스크의 파일은 유지됩니다.",
        modelName          : "이름",
        addLocalFile       : "로컬 파일 추가…",
        manageModels       : "온디바이스 AI 관리…",
        selectGgufModel    : "GGUF 모델 선택",
        suggested          : "추천",
        backendUrl      : "백엔드 URL",
        backendSubtitle : "이 앱을 Mirobody 백엔드 인스턴스로 연결하세요.",
        backendHint     : "비워 두면 현재 서버를 사용합니다.",
        invalidUrl      : "유효한 http(s) URL이 아닙니다",
        save            : "저장",
        cancel          : "취소",
        signOut         : "로그아웃",
        loginTitle      : "로그인",
        loginSubtitle   : "일회용 코드를 이메일로 보내드립니다.",
        authOr          : "또는",
        continueWithGoogle : "Google로 계속",
        googleFailed    : "Google 로그인 실패",
        continueWithWeChat : "WeChat로 계속",
        wechatFailed    : "WeChat 로그인 실패",
        continueWithApple : "Apple로 계속",
        appleFailed     : "Apple 로그인 실패",
        continueWithGitHub : "GitHub로 계속",
        githubFailed    : "GitHub 로그인 실패",
        continueWithX   : "X로 계속",
        xFailed         : "X 로그인 실패",
        sendCode        : "코드 보내기",
        resendCode      : "코드 다시 보내기",
        resendIn        : "%s초 후 다시 보내기",
        verifyButton    : "확인",
        selectModel     : "모델 선택",
        emptyTitle      : "대화 시작하기",
        emptySubtitle   : "아래에서 모델을 선택한 후 첫 메시지를 보내세요.",
        messageHint     : "무엇이든 물어보세요",
        send            : "보내기",
        statsTitle      : "응답 세부정보",
        statsModel      : "모델",
        statsInput      : "입력 토큰",
        statsOutput     : "출력 토큰",
        statsTotalTokens : "전체 토큰",
        statsTotalCost  : "총 비용",
        close           : "닫기",
        copyReply       : "답변 복사",
        emailRequired   : "이메일을 입력하세요",
        sendingCode     : "코드 보내는 중…",
        codeSentTo      : "%s 로 코드를 보냈습니다.",
        sendFailed      : "코드 전송에 실패했습니다.",
        enterCode       : "이메일로 받은 코드를 입력하세요.",
        verifying       : "확인 중…",
        verifyFailed    : "인증에 실패했습니다.",
        badResponse     : "서버 응답 형식이 올바르지 않습니다.",
        requestFailed   : "문제가 발생했습니다.",
        historyTitle    : "기록",
        historyEmpty    : "기록이 없습니다.",
        historyUntitled : "제목 없음",
        historyLoadFailed : "기록을 불러오지 못했습니다.",
        historyDeleteTitle : "이 대화를 삭제하시겠습니까?",
        historyDeleteMessage : "이 대화는 영구적으로 삭제됩니다.",
        delete          : "삭제",
        retry           : "다시 시도",
        back            : "뒤로",
        menuTitle       : "메뉴",
        newChat         : "새 대화",
        addAccount      : "계정 추가",
        incognitoMode   : "시크릿 모드",
        incognitoStart  : "시크릿 모드 켜기",
        incognitoStop   : "시크릿 모드 끄기",
        incognitoHeading : "시크릿 모드입니다",
        incognitoNote   : "시크릿 대화는 저장되거나 메모리에 추가되지 않습니다.",
        signOutConfirm  : "로그아웃하시겠습니까?",
        sharedByBadge   : "%s 님이 공유함",
        sharedWithBadge : "%s 명과 공유 중",
        healthData      : "건강 및 데이터",
        bluetoothDevices : "블루투스 기기",
        bleTitle        : "블루투스 건강 기기",
        bleIntro        : "표준 블루투스 LE 센서(심박 스트랩, 혈압계, 체온계)를 연결합니다. 측정값은 건강 기록에 저장됩니다. 워치와 링은 독자 프로토콜을 사용하므로 「연결된 기기」에서 연결하세요.",
        bleScan         : "검색",
        bleScanning     : "검색 중…",
        bleStop         : "중지",
        bleDisconnect   : "연결 해제",
        bleNoDevices    : "아직 기기가 없습니다 — 검색을 누르세요",
        bleSupportedTag : "건강",
        bleSaved        : "%s건 저장됨",
        bleFailedSuffix : ", 실패 %s건",
        ehrConnect      : "EHR 연결",
        ehrConnectTitle : "내 EHR 연결",
        ehrConnectSubtitle : "병원이나 클리닉을 검색한 다음 로그인하여 기록을 공유하세요(SMART on FHIR).",
        ehrManualLabel  : "또는 FHIR 기본 URL 입력",
        ehrConnectBtn   : "연결",
        ehrSearchPlaceholder : "기관 검색(예: 병원 이름)",
        ehrSearch       : "검색",
        ehrSearching    : "검색 중…",
        ehrNoResults    : "일치하는 기관이 없습니다.",
        ehrConnecting   : "연결 중…",
        ehrSyncNow      : "지금 동기화",
        ehrConnectedTitle : "EHR 연결됨",
        ehrConnectedMsg : "내 EHR이 연결되었습니다. 지금 데이터를 동기화할까요?",
        ehrSyncDoneTitle : "동기화 완료",
        ehrSyncDoneMsg  : "관측 데이터 %s건을 가져왔습니다.",
        ehrErrorTitle   : "EHR 오류",
        ehrErrorMsg     : "요청을 완료할 수 없습니다. 다시 시도해 주세요.",
        ehrOk           : "확인",
        vendorManageTitle : "연결된 기기",
        vendorManageSubtitle : "기기 또는 서비스를 연결하거나 연결 해제합니다.",
        vendorNone      : "아직 연결된 기기가 없습니다.",
        vendorPending   : "대기 중",
        vendorConnect   : "연결",
        vendorGroupDevices : "기기",
        vendorGroupPlatforms : "플랫폼",
        vendorUnlink    : "연결 해제",
        vendorUnlinkTitle : "기기 연결 해제",
        vendorUnlinkMsg : "%s 연결을 해제할까요?"
    },
    fr: {
        settings        : "Paramètres",
        language        : "Langue",
        fontSize        : "Taille du texte",
        fontSmaller     : "Très petit",
        fontSmall       : "Petit",
        fontNormal      : "Normal",
        fontLarge       : "Grand",
        fontLarger      : "Très grand",
        backend         : "Serveur",
        onDeviceAi      : "IA sur l'appareil",
        onDeviceIntro      : "Les modèles s'exécutent entièrement sur votre appareil — hors ligne et privé. Ajoutez ici n'importe quel GGUF (téléchargement par URL ou fichier local) ; choisissez celui à utiliser dans la liste déroulante au-dessus de la zone de chat.",
        modelReady         : "prêt",
        modelDownloading   : "téléchargement",
        modelNotDownloaded : "non téléchargé",
        modelFileMissing   : "fichier manquant",
        download           : "Télécharger",
        add                : "Ajouter",
        deleteModel        : "Supprimer le modèle",
        forgetModel        : "Retirer (conserve le fichier)",
        deleteModelConfirm : "Supprimer « %s » ? Le fichier téléchargé sera retiré du disque.",
        forgetModelConfirm : "Retirer « %s » de la liste ? Votre fichier sur le disque est conservé.",
        modelName          : "Nom",
        addLocalFile       : "Ajouter un fichier local…",
        manageModels       : "Gérer l'IA sur l'appareil…",
        selectGgufModel    : "Sélectionner un modèle GGUF",
        suggested          : "Suggérés",
        backendUrl      : "URL du serveur",
        backendSubtitle : "Connectez cette application à une instance de serveur Mirobody.",
        backendHint     : "Laissez vide pour utiliser ce serveur.",
        invalidUrl      : "URL http(s) invalide",
        save            : "Enregistrer",
        cancel          : "Annuler",
        signOut         : "Se déconnecter",
        loginTitle      : "Se connecter",
        loginSubtitle   : "Nous vous enverrons un code à usage unique par e-mail.",
        authOr          : "ou",
        continueWithGoogle : "Continuer avec Google",
        googleFailed    : "Échec de la connexion Google",
        continueWithWeChat : "Continuer avec WeChat",
        wechatFailed    : "Échec de la connexion WeChat",
        continueWithApple : "Continuer avec Apple",
        appleFailed     : "Échec de la connexion Apple",
        continueWithGitHub : "Continuer avec GitHub",
        githubFailed    : "Échec de la connexion GitHub",
        continueWithX   : "Continuer avec X",
        xFailed         : "Échec de la connexion X",
        sendCode        : "Envoyer le code",
        resendCode      : "Renvoyer le code",
        resendIn        : "Renvoyer dans %s s",
        verifyButton    : "Vérifier",
        selectModel     : "Choisir un modèle",
        emptyTitle      : "Démarrer une conversation",
        emptySubtitle   : "Choisissez un modèle ci-dessous, puis envoyez votre premier message.",
        messageHint     : "Posez n'importe quelle question",
        send            : "Envoyer",
        statsTitle      : "Détails de la réponse",
        statsModel      : "Modèle",
        statsInput      : "Tokens d'entrée",
        statsOutput     : "Tokens de sortie",
        statsTotalTokens : "Total des tokens",
        statsTotalCost  : "Coût total",
        close           : "Fermer",
        copyReply       : "Copier la réponse",
        emailRequired   : "L'e-mail est requis",
        sendingCode     : "Envoi du code…",
        codeSentTo      : "Code envoyé à %s.",
        sendFailed      : "Échec de l'envoi du code.",
        enterCode       : "Saisissez le code reçu par e-mail.",
        verifying       : "Vérification…",
        verifyFailed    : "Échec de la vérification.",
        badResponse     : "Réponse inattendue du serveur.",
        requestFailed   : "Une erreur est survenue.",
        historyTitle    : "Historique",
        historyEmpty    : "Aucun historique.",
        historyUntitled : "Sans titre",
        historyLoadFailed : "Échec du chargement de l'historique.",
        historyDeleteTitle : "Supprimer cette conversation ?",
        historyDeleteMessage : "Cette conversation sera définitivement supprimée.",
        delete          : "Supprimer",
        retry           : "Réessayer",
        back            : "Retour",
        menuTitle       : "Menu",
        newChat         : "Nouvelle discussion",
        addAccount      : "Ajouter un compte",
        incognitoMode   : "Navigation privée",
        incognitoStart  : "Activer la navigation privée",
        incognitoStop   : "Désactiver la navigation privée",
        incognitoHeading : "Vous êtes en navigation privée",
        incognitoNote   : "Les conversations privées ne sont pas enregistrées ni ajoutées à la mémoire.",
        signOutConfirm  : "Se déconnecter de Mirobody ?",
        sharedByBadge   : "Partagé par %s",
        sharedWithBadge : "Partagé avec %s",
        healthData      : "Santé et données",
        bluetoothDevices : "Appareils Bluetooth",
        bleTitle        : "Appareils de santé Bluetooth",
        bleIntro        : "Connectez un capteur Bluetooth LE standard (ceinture cardio, brassard de tension, thermomètre). Les mesures sont enregistrées dans votre dossier de santé. Les montres et bagues utilisent des protocoles propriétaires — connectez-les dans « Appareils connectés ».",
        bleScan         : "Rechercher",
        bleScanning     : "Recherche…",
        bleStop         : "Arrêter",
        bleDisconnect   : "Déconnecter",
        bleNoDevices    : "Aucun appareil — appuyez sur Rechercher",
        bleSupportedTag : "santé",
        bleSaved        : "%s mesure(s) enregistrée(s)",
        bleFailedSuffix : ", %s échouée(s)",
        ehrConnect      : "Connecter un DSE",
        ehrConnectTitle : "Connecter mon DSE",
        ehrConnectSubtitle : "Recherchez un hôpital ou une clinique, puis connectez-vous pour partager vos dossiers (SMART on FHIR).",
        ehrManualLabel  : "Ou saisissez une URL de base FHIR",
        ehrConnectBtn   : "Connecter",
        ehrSearchPlaceholder : "Rechercher des établissements (ex. nom d'hôpital)",
        ehrSearch       : "Rechercher",
        ehrSearching    : "Recherche…",
        ehrNoResults    : "Aucun établissement correspondant.",
        ehrConnecting   : "Connexion…",
        ehrSyncNow      : "Synchroniser",
        ehrConnectedTitle : "DSE connecté",
        ehrConnectedMsg : "Mon DSE est connecté. Synchroniser maintenant ?",
        ehrSyncDoneTitle : "Synchronisation terminée",
        ehrSyncDoneMsg  : "%s observations importées.",
        ehrErrorTitle   : "Erreur DSE",
        ehrErrorMsg     : "Impossible de terminer la requête. Veuillez réessayer.",
        ehrOk           : "OK",
        vendorManageTitle : "Appareils connectés",
        vendorManageSubtitle : "Connectez ou déconnectez un appareil ou un service.",
        vendorNone      : "Aucun appareil connecté pour le moment.",
        vendorPending   : "En attente",
        vendorConnect   : "Connecter",
        vendorGroupDevices : "Appareils",
        vendorGroupPlatforms : "Plateformes",
        vendorUnlink    : "Déconnecter",
        vendorUnlinkTitle : "Déconnecter l'appareil",
        vendorUnlinkMsg : "Déconnecter %s ?"
    },
    de: {
        settings        : "Einstellungen",
        language        : "Sprache",
        fontSize        : "Schriftgröße",
        fontSmaller     : "Sehr klein",
        fontSmall       : "Klein",
        fontNormal      : "Normal",
        fontLarge       : "Groß",
        fontLarger      : "Sehr groß",
        backend         : "Backend",
        onDeviceAi      : "KI auf dem Gerät",
        onDeviceIntro      : "Modelle laufen vollständig auf deinem Gerät – offline und privat. Füge hier ein beliebiges GGUF hinzu (Download per URL oder lokale Datei); wähle im Modell-Dropdown über dem Chatfeld aus, welches verwendet wird.",
        modelReady         : "bereit",
        modelDownloading   : "wird geladen",
        modelNotDownloaded : "nicht geladen",
        modelFileMissing   : "Datei fehlt",
        download           : "Herunterladen",
        add                : "Hinzufügen",
        deleteModel        : "Modell löschen",
        forgetModel        : "Entfernen (Datei bleibt)",
        deleteModelConfirm : "„%s“ löschen? Die heruntergeladene Datei wird von der Festplatte entfernt.",
        forgetModelConfirm : "„%s“ aus der Liste entfernen? Deine Datei auf der Festplatte bleibt erhalten.",
        modelName          : "Name",
        addLocalFile       : "Lokale Datei hinzufügen…",
        manageModels       : "KI auf dem Gerät verwalten…",
        selectGgufModel    : "GGUF-Modell auswählen",
        suggested          : "Empfohlen",
        backendUrl      : "Backend-URL",
        backendSubtitle : "Verbinden Sie diese App mit einer Mirobody-Backend-Instanz.",
        backendHint     : "Leer lassen, um diesen Server zu verwenden.",
        invalidUrl      : "Keine gültige http(s)-URL",
        save            : "Speichern",
        cancel          : "Abbrechen",
        signOut         : "Abmelden",
        loginTitle      : "Anmelden",
        loginSubtitle   : "Wir senden Ihnen einen Einmalcode per E-Mail.",
        authOr          : "oder",
        continueWithGoogle : "Mit Google fortfahren",
        googleFailed    : "Google-Anmeldung fehlgeschlagen",
        continueWithWeChat : "Mit WeChat fortfahren",
        wechatFailed    : "WeChat-Anmeldung fehlgeschlagen",
        continueWithApple : "Mit Apple fortfahren",
        appleFailed     : "Apple-Anmeldung fehlgeschlagen",
        continueWithGitHub : "Mit GitHub fortfahren",
        githubFailed    : "GitHub-Anmeldung fehlgeschlagen",
        continueWithX   : "Mit X fortfahren",
        xFailed         : "X-Anmeldung fehlgeschlagen",
        sendCode        : "Code senden",
        resendCode      : "Code erneut senden",
        resendIn        : "Erneut senden in %s s",
        verifyButton    : "Bestätigen",
        selectModel     : "Modell wählen",
        emptyTitle      : "Konversation beginnen",
        emptySubtitle   : "Wählen Sie unten ein Modell und senden Sie Ihre erste Nachricht.",
        messageHint     : "Beliebige Frage stellen",
        send            : "Senden",
        statsTitle      : "Antwortdetails",
        statsModel      : "Modell",
        statsInput      : "Eingabe-Tokens",
        statsOutput     : "Ausgabe-Tokens",
        statsTotalTokens : "Tokens insgesamt",
        statsTotalCost  : "Gesamtkosten",
        close           : "Schließen",
        copyReply       : "Antwort kopieren",
        emailRequired   : "E-Mail erforderlich",
        sendingCode     : "Code wird gesendet…",
        codeSentTo      : "Code an %s gesendet.",
        sendFailed      : "Code konnte nicht gesendet werden.",
        enterCode       : "Geben Sie den Code aus Ihrer E-Mail ein.",
        verifying       : "Wird bestätigt…",
        verifyFailed    : "Bestätigung fehlgeschlagen.",
        badResponse     : "Unerwartete Antwort vom Server.",
        requestFailed   : "Etwas ist schiefgegangen.",
        historyTitle    : "Verlauf",
        historyEmpty    : "Noch kein Verlauf.",
        historyUntitled : "Ohne Titel",
        historyLoadFailed : "Verlauf konnte nicht geladen werden.",
        historyDeleteTitle : "Konversation löschen?",
        historyDeleteMessage : "Diese Konversation wird endgültig entfernt.",
        delete          : "Löschen",
        retry           : "Erneut versuchen",
        back            : "Zurück",
        menuTitle       : "Menü",
        newChat         : "Neuer Chat",
        addAccount      : "Konto hinzufügen",
        incognitoMode   : "Inkognito",
        incognitoStart  : "Inkognito aktivieren",
        incognitoStop   : "Inkognito deaktivieren",
        incognitoHeading : "Inkognito-Modus aktiv",
        incognitoNote   : "Inkognito-Chats werden nicht gespeichert oder zum Speicher hinzugefügt.",
        signOutConfirm  : "Von Mirobody abmelden?",
        sharedByBadge   : "Geteilt von %s",
        sharedWithBadge : "Geteilt mit %s",
        healthData      : "Gesundheit & Daten",
        bluetoothDevices : "Bluetooth-Geräte",
        bleTitle        : "Bluetooth-Gesundheitsgeräte",
        bleIntro        : "Verbinde einen Standard-Bluetooth-LE-Sensor (Herzfrequenzgurt, Blutdruckmanschette, Thermometer). Messwerte werden in deiner Gesundheitsakte gespeichert. Uhren und Ringe nutzen proprietäre Protokolle — verbinde sie unter „Verbundene Geräte“.",
        bleScan         : "Suchen",
        bleScanning     : "Suche…",
        bleStop         : "Stopp",
        bleDisconnect   : "Trennen",
        bleNoDevices    : "Noch keine Geräte — auf Suchen tippen",
        bleSupportedTag : "Gesundheit",
        bleSaved        : "%s Messwert(e) gespeichert",
        bleFailedSuffix : ", %s fehlgeschlagen",
        ehrConnect      : "EHR verbinden",
        ehrConnectTitle : "Mein EHR verbinden",
        ehrConnectSubtitle : "Suche nach einem Krankenhaus oder einer Klinik und melde dich an, um deine Daten zu teilen (SMART on FHIR).",
        ehrManualLabel  : "Oder eine FHIR-Basis-URL eingeben",
        ehrConnectBtn   : "Verbinden",
        ehrSearchPlaceholder : "Anbieter suchen (z. B. Krankenhausname)",
        ehrSearch       : "Suchen",
        ehrSearching    : "Suche…",
        ehrNoResults    : "Keine passenden Anbieter.",
        ehrConnecting   : "Verbinde…",
        ehrSyncNow      : "Jetzt synchronisieren",
        ehrConnectedTitle : "Gesundheitsakte verbunden",
        ehrConnectedMsg : "Meine Gesundheitsakte ist verbunden. Daten jetzt synchronisieren?",
        ehrSyncDoneTitle : "Synchronisierung abgeschlossen",
        ehrSyncDoneMsg  : "%s Beobachtungen importiert.",
        ehrErrorTitle   : "EHR-Fehler",
        ehrErrorMsg     : "Anfrage konnte nicht abgeschlossen werden. Bitte erneut versuchen.",
        ehrOk           : "OK",
        vendorManageTitle : "Verbundene Geräte",
        vendorManageSubtitle : "Ein Gerät oder einen Dienst verbinden oder trennen.",
        vendorNone      : "Noch keine verbundenen Geräte.",
        vendorPending   : "Ausstehend",
        vendorConnect   : "Verbinden",
        vendorGroupDevices : "Geräte",
        vendorGroupPlatforms : "Plattformen",
        vendorUnlink    : "Trennen",
        vendorUnlinkTitle : "Gerät trennen",
        vendorUnlinkMsg : "%s trennen?"
    },
    ru: {
        settings        : "Настройки",
        language        : "Язык",
        fontSize        : "Размер шрифта",
        fontSmaller     : "Очень мелкий",
        fontSmall       : "Мелкий",
        fontNormal      : "Обычный",
        fontLarge       : "Крупный",
        fontLarger      : "Очень крупный",
        backend         : "Сервер",
        onDeviceAi      : "ИИ на устройстве",
        onDeviceIntro      : "Модели работают полностью на вашем устройстве — офлайн и приватно. Добавьте здесь любой GGUF (загрузка по URL или локальный файл); выберите используемую модель в списке над полем чата.",
        modelReady         : "готово",
        modelDownloading   : "загрузка",
        modelNotDownloaded : "не загружено",
        modelFileMissing   : "файл отсутствует",
        download           : "Скачать",
        add                : "Добавить",
        deleteModel        : "Удалить модель",
        forgetModel        : "Убрать (файл остаётся)",
        deleteModelConfirm : "Удалить «%s»? Загруженный файл будет удалён с диска.",
        forgetModelConfirm : "Убрать «%s» из списка? Ваш файл на диске сохранится.",
        modelName          : "Имя",
        addLocalFile       : "Добавить локальный файл…",
        manageModels       : "Управление ИИ на устройстве…",
        selectGgufModel    : "Выберите модель GGUF",
        suggested          : "Рекомендуемые",
        backendUrl      : "URL сервера",
        backendSubtitle : "Укажите экземпляр сервера Mirobody для этого приложения.",
        backendHint     : "Оставьте пустым, чтобы использовать этот сервер.",
        invalidUrl      : "Неверный http(s) URL",
        save            : "Сохранить",
        cancel          : "Отмена",
        signOut         : "Выйти",
        loginTitle      : "Войти",
        loginSubtitle   : "Мы отправим вам одноразовый код по электронной почте.",
        authOr          : "или",
        continueWithGoogle : "Продолжить через Google",
        googleFailed    : "Не удалось войти через Google",
        continueWithWeChat : "Продолжить через WeChat",
        wechatFailed    : "Не удалось войти через WeChat",
        continueWithApple : "Продолжить через Apple",
        appleFailed     : "Не удалось войти через Apple",
        continueWithGitHub : "Продолжить через GitHub",
        githubFailed    : "Не удалось войти через GitHub",
        continueWithX   : "Продолжить через X",
        xFailed         : "Не удалось войти через X",
        sendCode        : "Отправить код",
        resendCode      : "Отправить заново",
        resendIn        : "Повтор через %s сек",
        verifyButton    : "Подтвердить",
        selectModel     : "Выбрать модель",
        emptyTitle      : "Начните разговор",
        emptySubtitle   : "Выберите модель ниже и отправьте первое сообщение.",
        messageHint     : "Спросите о чём угодно",
        send            : "Отправить",
        statsTitle      : "Детали ответа",
        statsModel      : "Модель",
        statsInput      : "Входные токены",
        statsOutput     : "Выходные токены",
        statsTotalTokens : "Всего токенов",
        statsTotalCost  : "Общая стоимость",
        close           : "Закрыть",
        copyReply       : "Копировать ответ",
        emailRequired   : "Введите эл. почту",
        sendingCode     : "Отправка кода…",
        codeSentTo      : "Код отправлен на %s.",
        sendFailed      : "Не удалось отправить код.",
        enterCode       : "Введите код из письма.",
        verifying       : "Проверка…",
        verifyFailed    : "Не удалось подтвердить.",
        badResponse     : "Неожиданный ответ от сервера.",
        requestFailed   : "Что-то пошло не так.",
        historyTitle    : "История",
        historyEmpty    : "История пуста.",
        historyUntitled : "Без названия",
        historyLoadFailed : "Не удалось загрузить историю.",
        historyDeleteTitle : "Удалить эту переписку?",
        historyDeleteMessage : "Эта переписка будет удалена навсегда.",
        delete          : "Удалить",
        retry           : "Повторить",
        back            : "Назад",
        menuTitle       : "Меню",
        newChat         : "Новый чат",
        addAccount      : "Добавить аккаунт",
        incognitoMode   : "Инкогнито",
        incognitoStart  : "Включить инкогнито",
        incognitoStop   : "Выключить инкогнито",
        incognitoHeading : "Режим инкогнито",
        incognitoNote   : "Чаты в режиме инкогнито не сохраняются и не добавляются в память.",
        signOutConfirm  : "Выйти из Mirobody?",
        sharedByBadge   : "Поделился %s",
        sharedWithBadge : "Открыт доступ: %s",
        healthData      : "Здоровье и данные",
        bluetoothDevices : "Bluetooth-устройства",
        bleTitle        : "Bluetooth-устройства для здоровья",
        bleIntro        : "Подключите стандартный датчик Bluetooth LE (нагрудный пульсометр, манжету давления, термометр). Показания сохраняются в вашей медицинской карте. Часы и кольца используют закрытые протоколы — подключайте их в разделе «Подключённые устройства».",
        bleScan         : "Поиск",
        bleScanning     : "Поиск…",
        bleStop         : "Стоп",
        bleDisconnect   : "Отключить",
        bleNoDevices    : "Пока нет устройств — нажмите «Поиск»",
        bleSupportedTag : "здоровье",
        bleSaved        : "Сохранено: %s",
        bleFailedSuffix : ", не удалось: %s",
        ehrConnect      : "Подключить ЭМК",
        ehrConnectTitle : "Подключить мою ЭМК",
        ehrConnectSubtitle : "Найдите больницу или клинику, затем войдите, чтобы делиться своими записями (SMART on FHIR).",
        ehrManualLabel  : "Или введите базовый URL FHIR",
        ehrConnectBtn   : "Подключить",
        ehrSearchPlaceholder : "Поиск учреждений (напр. название больницы)",
        ehrSearch       : "Найти",
        ehrSearching    : "Поиск…",
        ehrNoResults    : "Подходящих учреждений нет.",
        ehrConnecting   : "Подключение…",
        ehrSyncNow      : "Синхронизировать",
        ehrConnectedTitle : "ЭМК подключена",
        ehrConnectedMsg : "Моя ЭМК подключена. Синхронизировать данные сейчас?",
        ehrSyncDoneTitle : "Синхронизация завершена",
        ehrSyncDoneMsg  : "Импортировано наблюдений: %s.",
        ehrErrorTitle   : "Ошибка ЭМК",
        ehrErrorMsg     : "Не удалось выполнить запрос. Попробуйте ещё раз.",
        ehrOk           : "ОК",
        vendorManageTitle : "Подключённые устройства",
        vendorManageSubtitle : "Подключение или отключение устройства либо сервиса.",
        vendorNone      : "Пока нет подключённых устройств.",
        vendorPending   : "Ожидание",
        vendorConnect   : "Подключить",
        vendorGroupDevices : "Устройства",
        vendorGroupPlatforms : "Платформы",
        vendorUnlink    : "Отключить",
        vendorUnlinkTitle : "Отключить устройство",
        vendorUnlinkMsg : "Отключить %s?"
    },
    es: {
        settings        : "Ajustes",
        language        : "Idioma",
        fontSize        : "Tamaño de fuente",
        fontSmaller     : "Muy pequeño",
        fontSmall       : "Pequeño",
        fontNormal      : "Normal",
        fontLarge       : "Grande",
        fontLarger      : "Muy grande",
        backend         : "Servidor",
        onDeviceAi      : "IA en el dispositivo",
        onDeviceIntro      : "Los modelos se ejecutan completamente en tu dispositivo, sin conexión y de forma privada. Añade aquí cualquier GGUF (descarga por URL o archivo local); elige cuál usar en el menú desplegable sobre el chat.",
        modelReady         : "listo",
        modelDownloading   : "descargando",
        modelNotDownloaded : "no descargado",
        modelFileMissing   : "archivo ausente",
        download           : "Descargar",
        add                : "Añadir",
        deleteModel        : "Eliminar modelo",
        forgetModel        : "Quitar (conserva el archivo)",
        deleteModelConfirm : "¿Eliminar «%s»? El archivo descargado se quitará del disco.",
        forgetModelConfirm : "¿Quitar «%s» de la lista? Tu archivo en el disco se conserva.",
        modelName          : "Nombre",
        addLocalFile       : "Añadir archivo local…",
        manageModels       : "Gestionar IA en el dispositivo…",
        selectGgufModel    : "Seleccionar un modelo GGUF",
        suggested          : "Sugeridos",
        backendUrl      : "URL del servidor",
        backendSubtitle : "Apunta esta app a una instancia del servidor Mirobody.",
        backendHint     : "Déjalo en blanco para usar este servidor.",
        invalidUrl      : "URL http(s) no válida",
        save            : "Guardar",
        cancel          : "Cancelar",
        signOut         : "Cerrar sesión",
        loginTitle      : "Iniciar sesión",
        loginSubtitle   : "Te enviaremos un código de un solo uso por correo.",
        authOr          : "o",
        continueWithGoogle : "Continuar con Google",
        googleFailed    : "Error al iniciar sesión con Google",
        continueWithWeChat : "Continuar con WeChat",
        wechatFailed    : "Error al iniciar sesión con WeChat",
        continueWithApple : "Continuar con Apple",
        appleFailed     : "Error al iniciar sesión con Apple",
        continueWithGitHub : "Continuar con GitHub",
        githubFailed    : "Error al iniciar sesión con GitHub",
        continueWithX   : "Continuar con X",
        xFailed         : "Error al iniciar sesión con X",
        sendCode        : "Enviar código",
        resendCode      : "Reenviar código",
        resendIn        : "Reenviar en %s s",
        verifyButton    : "Verificar",
        selectModel     : "Elegir modelo",
        emptyTitle      : "Iniciar una conversación",
        emptySubtitle   : "Elige un modelo abajo y envía tu primer mensaje.",
        messageHint     : "Pregunta lo que quieras",
        send            : "Enviar",
        statsTitle      : "Detalles de la respuesta",
        statsModel      : "Modelo",
        statsInput      : "Tokens de entrada",
        statsOutput     : "Tokens de salida",
        statsTotalTokens : "Tokens totales",
        statsTotalCost  : "Coste total",
        close           : "Cerrar",
        copyReply       : "Copiar respuesta",
        emailRequired   : "Se requiere correo",
        sendingCode     : "Enviando código…",
        codeSentTo      : "Código enviado a %s.",
        sendFailed      : "No se pudo enviar el código.",
        enterCode       : "Introduce el código de tu correo.",
        verifying       : "Verificando…",
        verifyFailed    : "Error de verificación.",
        badResponse     : "Respuesta inesperada del servidor.",
        requestFailed   : "Algo salió mal.",
        historyTitle    : "Historial",
        historyEmpty    : "Sin historial todavía.",
        historyUntitled : "Sin título",
        historyLoadFailed : "No se pudo cargar el historial.",
        historyDeleteTitle : "¿Eliminar esta conversación?",
        historyDeleteMessage : "Esta conversación se eliminará permanentemente.",
        delete          : "Eliminar",
        retry           : "Reintentar",
        back            : "Atrás",
        menuTitle       : "Menú",
        newChat         : "Nuevo chat",
        addAccount      : "Añadir cuenta",
        incognitoMode   : "Incógnito",
        incognitoStart  : "Activar modo incógnito",
        incognitoStop   : "Desactivar modo incógnito",
        incognitoHeading : "Estás en modo incógnito",
        incognitoNote   : "Los chats en incógnito no se guardan ni se añaden a la memoria.",
        signOutConfirm  : "¿Cerrar sesión en Mirobody?",
        sharedByBadge   : "Compartido por %s",
        sharedWithBadge : "Compartido con %s",
        healthData      : "Salud y datos",
        bluetoothDevices : "Dispositivos Bluetooth",
        bleTitle        : "Dispositivos de salud Bluetooth",
        bleIntro        : "Conecta un sensor Bluetooth LE estándar (banda de frecuencia cardíaca, tensiómetro, termómetro). Las lecturas se guardan en tu historial de salud. Los relojes y anillos usan protocolos propios: conéctalos en «Dispositivos conectados».",
        bleScan         : "Buscar",
        bleScanning     : "Buscando…",
        bleStop         : "Detener",
        bleDisconnect   : "Desconectar",
        bleNoDevices    : "Aún no hay dispositivos: toca Buscar",
        bleSupportedTag : "salud",
        bleSaved        : "%s lectura(s) guardada(s)",
        bleFailedSuffix : ", %s fallida(s)",
        ehrConnect      : "Conectar HCE",
        ehrConnectTitle : "Conectar mi HCE",
        ehrConnectSubtitle : "Busca un hospital o clínica y luego inicia sesión para compartir tus registros (SMART on FHIR).",
        ehrManualLabel  : "O introduce una URL base de FHIR",
        ehrConnectBtn   : "Conectar",
        ehrSearchPlaceholder : "Buscar centros (p. ej. nombre del hospital)",
        ehrSearch       : "Buscar",
        ehrSearching    : "Buscando…",
        ehrNoResults    : "No hay proveedores coincidentes.",
        ehrConnecting   : "Conectando…",
        ehrSyncNow      : "Sincronizar ahora",
        ehrConnectedTitle : "HCE conectada",
        ehrConnectedMsg : "Mi HCE está conectada. ¿Sincronizar ahora?",
        ehrSyncDoneTitle : "Sincronización completa",
        ehrSyncDoneMsg  : "Se importaron %s observaciones.",
        ehrErrorTitle   : "Error de HCE",
        ehrErrorMsg     : "No se pudo completar la solicitud. Inténtalo de nuevo.",
        ehrOk           : "Aceptar",
        vendorManageTitle : "Dispositivos conectados",
        vendorManageSubtitle : "Conecta o desconecta un dispositivo o servicio.",
        vendorNone      : "Aún no hay dispositivos conectados.",
        vendorPending   : "Pendiente",
        vendorConnect   : "Conectar",
        vendorGroupDevices : "Dispositivos",
        vendorGroupPlatforms : "Plataformas",
        vendorUnlink    : "Desconectar",
        vendorUnlinkTitle : "Desconectar dispositivo",
        vendorUnlinkMsg : "¿Desconectar %s?"
    },
    ar: {
        settings        : "الإعدادات",
        language        : "اللغة",
        fontSize        : "حجم الخط",
        fontSmaller     : "أصغر",
        fontSmall       : "صغير",
        fontNormal      : "عادي",
        fontLarge       : "كبير",
        fontLarger      : "أكبر",
        backend         : "الخادم",
        onDeviceAi      : "ذكاء اصطناعي على الجهاز",
        onDeviceIntro      : "تعمل النماذج بالكامل على جهازك — دون اتصال وبخصوصية. أضِف أي ملف GGUF هنا (تنزيل عبر رابط أو اختيار ملف محلي)؛ ثم اختر النموذج المستخدم من القائمة المنسدلة أعلى مربع المحادثة.",
        modelReady         : "جاهز",
        modelDownloading   : "جارٍ التنزيل",
        modelNotDownloaded : "غير مُنزَّل",
        modelFileMissing   : "الملف مفقود",
        download           : "تنزيل",
        add                : "إضافة",
        deleteModel        : "حذف النموذج",
        forgetModel        : "إزالة (يحتفظ بملفك)",
        deleteModelConfirm : "حذف ”%s“؟ سيُزال الملف الذي جرى تنزيله من القرص.",
        forgetModelConfirm : "إزالة ”%s“ من القائمة؟ سيبقى ملفك على القرص.",
        modelName          : "الاسم",
        addLocalFile       : "إضافة ملف محلي…",
        manageModels       : "إدارة الذكاء الاصطناعي على الجهاز…",
        selectGgufModel    : "اختر نموذج GGUF",
        suggested          : "مقترحة",
        backendUrl      : "عنوان الخادم",
        backendSubtitle : "وجّه هذا التطبيق إلى خادم Mirobody.",
        backendHint     : "اتركه فارغًا لاستخدام هذا الخادم.",
        invalidUrl      : "عنوان http(s) غير صالح",
        save            : "حفظ",
        cancel          : "إلغاء",
        signOut         : "تسجيل الخروج",
        loginTitle      : "تسجيل الدخول",
        loginSubtitle   : "سنرسل إليك رمزًا لمرة واحدة عبر البريد الإلكتروني.",
        authOr          : "أو",
        continueWithGoogle : "المتابعة باستخدام Google",
        googleFailed    : "فشل تسجيل الدخول عبر Google",
        continueWithWeChat : "المتابعة باستخدام WeChat",
        wechatFailed    : "فشل تسجيل الدخول عبر WeChat",
        continueWithApple : "المتابعة باستخدام Apple",
        appleFailed     : "فشل تسجيل الدخول عبر Apple",
        continueWithGitHub : "المتابعة باستخدام GitHub",
        githubFailed    : "فشل تسجيل الدخول عبر GitHub",
        continueWithX   : "المتابعة باستخدام X",
        xFailed         : "فشل تسجيل الدخول عبر X",
        sendCode        : "إرسال الرمز",
        resendCode      : "إعادة إرسال الرمز",
        resendIn        : "إعادة الإرسال خلال %s ثانية",
        verifyButton    : "تحقق",
        selectModel     : "اختر النموذج",
        emptyTitle      : "ابدأ محادثة",
        emptySubtitle   : "اختر نموذجًا بالأسفل ثم أرسل رسالتك الأولى.",
        messageHint     : "اسأل عن أي شيء",
        send            : "إرسال",
        statsTitle      : "تفاصيل الرد",
        statsModel      : "النموذج",
        statsInput      : "رموز الإدخال",
        statsOutput     : "رموز الإخراج",
        statsTotalTokens : "إجمالي الرموز",
        statsTotalCost  : "التكلفة الإجمالية",
        close           : "إغلاق",
        copyReply       : "نسخ الرد",
        emailRequired   : "البريد الإلكتروني مطلوب",
        sendingCode     : "جارٍ إرسال الرمز…",
        codeSentTo      : "تم إرسال الرمز إلى %s.",
        sendFailed      : "فشل إرسال الرمز.",
        enterCode       : "أدخل الرمز من بريدك الإلكتروني.",
        verifying       : "جارٍ التحقق…",
        verifyFailed    : "فشل التحقق.",
        badResponse     : "استجابة غير متوقعة من الخادم.",
        requestFailed   : "حدث خطأ ما.",
        historyTitle    : "السجل",
        historyEmpty    : "لا يوجد سجل بعد.",
        historyUntitled : "بدون عنوان",
        historyLoadFailed : "فشل تحميل السجل.",
        historyDeleteTitle : "حذف المحادثة؟",
        historyDeleteMessage : "ستُحذف هذه المحادثة نهائيًا.",
        delete          : "حذف",
        retry           : "إعادة المحاولة",
        back            : "رجوع",
        menuTitle       : "القائمة",
        newChat         : "محادثة جديدة",
        addAccount      : "إضافة حساب",
        incognitoMode   : "الوضع المتخفّي",
        incognitoStart  : "تفعيل الوضع المتخفّي",
        incognitoStop   : "إيقاف الوضع المتخفّي",
        incognitoHeading : "أنت في الوضع المتخفّي",
        incognitoNote   : "لا يتم حفظ المحادثات المتخفّية أو إضافتها إلى الذاكرة.",
        signOutConfirm  : "تسجيل الخروج من Mirobody؟",
        sharedByBadge   : "تمت المشاركة بواسطة %s",
        sharedWithBadge : "تمت المشاركة مع %s",
        healthData      : "الصحة والبيانات",
        bluetoothDevices : "أجهزة البلوتوث",
        bleTitle        : "أجهزة صحية عبر البلوتوث",
        bleIntro        : "وصّل مستشعر Bluetooth LE قياسيًا (حزام معدل ضربات القلب، كفة ضغط الدم، مقياس حرارة). تُحفظ القراءات في سجلك الصحي. تستخدم الساعات والخواتم بروتوكولات خاصة — وصّلها من «الأجهزة المتصلة».",
        bleScan         : "بحث",
        bleScanning     : "جارٍ البحث…",
        bleStop         : "إيقاف",
        bleDisconnect   : "فصل",
        bleNoDevices    : "لا توجد أجهزة بعد — اضغط على بحث",
        bleSupportedTag : "صحة",
        bleSaved        : "تم حفظ %s قراءة",
        bleFailedSuffix : "، فشل %s",
        ehrConnect      : "توصيل السجل الصحي",
        ehrConnectTitle : "توصيل سجلي الصحي",
        ehrConnectSubtitle : "ابحث عن مستشفى أو عيادة، ثم سجّل الدخول لمشاركة سجلاتك (SMART on FHIR).",
        ehrManualLabel  : "أو أدخل عنوان FHIR الأساسي",
        ehrConnectBtn   : "توصيل",
        ehrSearchPlaceholder : "ابحث عن مزوّدين (مثل اسم المستشفى)",
        ehrSearch       : "بحث",
        ehrSearching    : "جارٍ البحث…",
        ehrNoResults    : "لا توجد جهات مطابقة.",
        ehrConnecting   : "جارٍ الاتصال…",
        ehrSyncNow      : "مزامنة الآن",
        ehrConnectedTitle : "تم ربط السجل الصحي",
        ehrConnectedMsg : "تم ربط سجلي الصحي. هل تريد المزامنة الآن؟",
        ehrSyncDoneTitle : "اكتملت المزامنة",
        ehrSyncDoneMsg  : "تم استيراد %s قياسًا.",
        ehrErrorTitle   : "خطأ في السجل الصحي",
        ehrErrorMsg     : "تعذّر إكمال الطلب. حاول مرة أخرى.",
        ehrOk           : "حسناً",
        vendorManageTitle : "الأجهزة المتصلة",
        vendorManageSubtitle : "توصيل أو فصل جهاز أو خدمة.",
        vendorNone      : "لا توجد أجهزة متصلة بعد.",
        vendorPending   : "قيد الانتظار",
        vendorConnect   : "توصيل",
        vendorGroupDevices : "الأجهزة",
        vendorGroupPlatforms : "المنصّات",
        vendorUnlink    : "فصل",
        vendorUnlinkTitle : "فصل الجهاز",
        vendorUnlinkMsg : "هل تريد فصل %s؟"
    },
    he: {
        settings        : "הגדרות",
        language        : "שפה",
        fontSize        : "גודל גופן",
        fontSmaller     : "קטן מאוד",
        fontSmall       : "קטן",
        fontNormal      : "רגיל",
        fontLarge       : "גדול",
        fontLarger      : "גדול מאוד",
        backend         : "שרת",
        onDeviceAi      : "בינה מלאכותית במכשיר",
        onDeviceIntro      : "הדגמים פועלים כולם על המכשיר שלך — אופליין ופרטי. הוסף כאן כל GGUF (הורדה לפי כתובת או קובץ מקומי); בחר איזה להשתמש מהרשימה הנפתחת מעל תיבת הצ׳אט.",
        modelReady         : "מוכן",
        modelDownloading   : "מוריד",
        modelNotDownloaded : "לא הורד",
        modelFileMissing   : "הקובץ חסר",
        download           : "הורדה",
        add                : "הוסף",
        deleteModel        : "מחק דגם",
        forgetModel        : "הסר (הקובץ יישמר)",
        deleteModelConfirm : "למחוק את ”%s“? הקובץ שהורד יוסר מהדיסק.",
        forgetModelConfirm : "להסיר את ”%s“ מהרשימה? הקובץ שלך בדיסק יישמר.",
        modelName          : "שם",
        addLocalFile       : "הוסף קובץ מקומי…",
        manageModels       : "ניהול בינה מלאכותית במכשיר…",
        selectGgufModel    : "בחר מודל GGUF",
        suggested          : "מומלצים",
        backendUrl      : "כתובת השרת",
        backendSubtitle : "הפנה אפליקציה זו למופע שרת Mirobody.",
        backendHint     : "השאר ריק כדי להשתמש בשרת זה.",
        invalidUrl      : "כתובת http(s) לא תקינה",
        save            : "שמירה",
        cancel          : "ביטול",
        signOut         : "התנתקות",
        loginTitle      : "התחברות",
        loginSubtitle   : "נשלח לך קוד חד-פעמי באימייל.",
        authOr          : "או",
        continueWithGoogle : "המשך עם Google",
        googleFailed    : "ההתחברות עם Google נכשלה",
        continueWithWeChat : "המשך עם WeChat",
        wechatFailed    : "ההתחברות עם WeChat נכשלה",
        continueWithApple : "המשך עם Apple",
        appleFailed     : "ההתחברות עם Apple נכשלה",
        continueWithGitHub : "המשך עם GitHub",
        githubFailed    : "ההתחברות עם GitHub נכשלה",
        continueWithX   : "המשך עם X",
        xFailed         : "ההתחברות עם X נכשלה",
        sendCode        : "שליחת קוד",
        resendCode      : "שליחת קוד מחדש",
        resendIn        : "שליחה מחדש בעוד %s שניות",
        verifyButton    : "אימות",
        selectModel     : "בחר מודל",
        emptyTitle      : "התחל שיחה",
        emptySubtitle   : "בחר מודל למטה ושלח את ההודעה הראשונה שלך.",
        messageHint     : "שאל כל דבר",
        send            : "שליחה",
        statsTitle      : "פרטי התשובה",
        statsModel      : "מודל",
        statsInput      : "אסימוני קלט",
        statsOutput     : "אסימוני פלט",
        statsTotalTokens : "סך האסימונים",
        statsTotalCost  : "עלות כוללת",
        close           : "סגירה",
        copyReply       : "העתק תשובה",
        emailRequired   : "נדרש אימייל",
        sendingCode     : "שולח קוד…",
        codeSentTo      : "הקוד נשלח אל %s.",
        sendFailed      : "שליחת הקוד נכשלה.",
        enterCode       : "הזן את הקוד מהאימייל שלך.",
        verifying       : "מאמת…",
        verifyFailed    : "האימות נכשל.",
        badResponse     : "תגובה לא צפויה מהשרת.",
        requestFailed   : "משהו השתבש.",
        historyTitle    : "היסטוריה",
        historyEmpty    : "אין היסטוריה עדיין.",
        historyUntitled : "ללא כותרת",
        historyLoadFailed : "טעינת ההיסטוריה נכשלה.",
        historyDeleteTitle : "למחוק את השיחה?",
        historyDeleteMessage : "שיחה זו תימחק לצמיתות.",
        delete          : "מחיקה",
        retry           : "נסה שוב",
        back            : "חזרה",
        menuTitle       : "תפריט",
        newChat         : "שיחה חדשה",
        addAccount      : "הוספת חשבון",
        incognitoMode   : "מצב פרטי",
        incognitoStart  : "הפעלת מצב פרטי",
        incognitoStop   : "כיבוי מצב פרטי",
        incognitoHeading : "אתה במצב פרטי",
        incognitoNote   : "שיחות במצב פרטי אינן נשמרות ואינן מתווספות לזיכרון.",
        signOutConfirm  : "להתנתק מ‑Mirobody?",
        sharedByBadge   : "שותף על ידי %s",
        sharedWithBadge : "שותף עם %s",
        healthData      : "בריאות ונתונים",
        bluetoothDevices : "מכשירי Bluetooth",
        bleTitle        : "מכשירי בריאות Bluetooth",
        bleIntro        : "חברו חיישן Bluetooth LE סטנדרטי (רצועת דופק, שרוול לחץ דם, מדחום). הקריאות נשמרות ברשומה הרפואית שלכם. שעונים וטבעות משתמשים בפרוטוקולים סגורים — חברו אותם דרך «מכשירים מחוברים».",
        bleScan         : "סריקה",
        bleScanning     : "סורק…",
        bleStop         : "עצירה",
        bleDisconnect   : "ניתוק",
        bleNoDevices    : "אין עדיין מכשירים — הקישו על סריקה",
        bleSupportedTag : "בריאות",
        bleSaved        : "נשמרו %s קריאות",
        bleFailedSuffix : ", נכשלו %s",
        ehrConnect      : "חיבור תיק רפואי",
        ehrConnectTitle : "חיבור התיק הרפואי שלי",
        ehrConnectSubtitle : "חפשו בית חולים או מרפאה, ואז התחברו כדי לשתף את הרשומות שלכם (SMART on FHIR).",
        ehrManualLabel  : "או הזינו כתובת FHIR בסיסית",
        ehrConnectBtn   : "חיבור",
        ehrSearchPlaceholder : "חיפוש ספקים (למשל שם בית חולים)",
        ehrSearch       : "חיפוש",
        ehrSearching    : "מחפש…",
        ehrNoResults    : "אין ספקים תואמים.",
        ehrConnecting   : "מתחבר…",
        ehrSyncNow      : "סנכרון עכשיו",
        ehrConnectedTitle : "הרשומה הרפואית חוברה",
        ehrConnectedMsg : "הרשומה הרפואית שלי מחוברת. לסנכרן עכשיו?",
        ehrSyncDoneTitle : "הסנכרון הושלם",
        ehrSyncDoneMsg  : "יובאו %s תצפיות.",
        ehrErrorTitle   : "שגיאת רשומה רפואית",
        ehrErrorMsg     : "לא ניתן היה להשלים את הבקשה. נסה שוב.",
        ehrOk           : "אישור",
        vendorManageTitle : "מכשירים מחוברים",
        vendorManageSubtitle : "חיבור או ניתוק של מכשיר או שירות.",
        vendorNone      : "אין עדיין מכשירים מחוברים.",
        vendorPending   : "ממתין",
        vendorConnect   : "חיבור",
        vendorGroupDevices : "מכשירים",
        vendorGroupPlatforms : "פלטפורמות",
        vendorUnlink    : "ניתוק",
        vendorUnlinkTitle : "נתק מכשיר",
        vendorUnlinkMsg : "לנתק את %s?"
    }
};

// Look up a key in `lang`, falling back to English then to the key itself. A
// single "%s" placeholder is replaced when `arg` is provided. Mirrors i18n.t().
function tr(lang, key, arg) {
    var table = STRINGS[lang] || STRINGS.en;
    var s = table[key];
    if (s === undefined) { s = STRINGS.en[key]; }
    if (s === undefined) { return key; }
    if (arg !== undefined && arg !== null) { s = s.replace("%s", arg); }
    return s;
}