// AUTO-DERIVED from htdoc/src/i18n.js -- the UI string table for the ten
// languages the app offers, kept verbatim so the Qt client and the web client
// read identically. `.pragma library` makes this a shared, stateless module.
// Regenerate by re-copying the STRINGS object from i18n.js if it changes.

.pragma library
var STRINGS = {
    en: {
        settings        : "Settings",
        language        : "Language",
        fontSize        : "Font size",
        fontSmaller     : "Smaller",
        fontSmall       : "Small",
        fontNormal      : "Normal",
        fontLarge       : "Large",
        fontLarger      : "Larger",
        backend         : "Backend",
        backendUrl      : "Backend URL",
        backendSubtitle : "Point this app at a Mirobody backend instance.",
        backendHint     : "Leave blank to use this server.",
        invalidUrl      : "Not a valid http(s) URL",
        save            : "Save",
        cancel          : "Cancel",
        about           : "About",
        version         : "Version %s",
        signOut         : "Sign out",
        loginTitle      : "Sign in",
        loginSubtitle   : "We'll email you a one-time code.",
        authOr          : "or",
        continueWithGoogle : "Continue with Google",
        googleFailed    : "Google sign-in failed",
        continueWithWeChat : "Continue with WeChat",
        wechatFailed    : "WeChat sign-in failed",
        continueWithApple : "Continue with Apple",
        appleFailed     : "Apple sign-in failed",
        continueWithGitHub : "Continue with GitHub",
        githubFailed    : "GitHub sign-in failed",
        continueWithX   : "Continue with X",
        xFailed         : "X sign-in failed",
        sendCode        : "Send code",
        resendCode      : "Resend code",
        resendIn        : "Resend in %ss",
        verifyButton    : "Verify",
        selectModel     : "Select model",
        emptyTitle      : "Start a conversation",
        emptySubtitle   : "Pick a model below, then send your first message.",
        messageHint     : "Ask anything",
        send            : "Send",
        statsTitle      : "Response details",
        statsModel      : "Model",
        statsInput      : "Input tokens",
        statsOutput     : "Output tokens",
        statsTotalTokens : "Total tokens",
        statsTotalCost  : "Total cost",
        close           : "Close",
        copyReply       : "Copy reply",
        emailRequired   : "Email is required",
        sendingCode     : "Sending code…",
        codeSentTo      : "Code sent to %s.",
        sendFailed      : "Failed to send code.",
        enterCode       : "Enter the code from your email.",
        verifying       : "Verifying…",
        verifyFailed    : "Verification failed.",
        badResponse     : "Unexpected response from the server.",
        requestFailed   : "Something went wrong.",
        historyTitle    : "History",
        historyEmpty    : "No history yet.",
        historyUntitled : "Untitled",
        historyLoadFailed : "Failed to load history.",
        historyDeleteTitle : "Delete conversation?",
        historyDeleteMessage : "This conversation will be permanently removed.",
        delete          : "Delete",
        retry           : "Retry",
        back            : "Back"
    },
    zh: {
        settings        : "设置",
        language        : "语言",
        fontSize        : "字号",
        fontSmaller     : "更小",
        fontSmall       : "小",
        fontNormal      : "正常",
        fontLarge       : "大",
        fontLarger      : "更大",
        backend         : "后端",
        backendUrl      : "后端地址",
        backendSubtitle : "将此应用指向一个 Mirobody 后端实例。",
        backendHint     : "留空则使用当前服务器。",
        invalidUrl      : "不是有效的 http(s) URL",
        save            : "保存",
        cancel          : "取消",
        about           : "关于",
        version         : "版本 %s",
        signOut         : "退出登录",
        loginTitle      : "登录",
        loginSubtitle   : "我们会通过邮件发送一次性验证码。",
        authOr          : "或",
        continueWithGoogle : "使用 Google 继续",
        googleFailed    : "Google 登录失败",
        continueWithWeChat : "使用微信继续",
        wechatFailed    : "微信登录失败",
        continueWithApple : "使用 Apple 继续",
        appleFailed     : "Apple 登录失败",
        continueWithGitHub : "使用 GitHub 继续",
        githubFailed    : "GitHub 登录失败",
        continueWithX   : "使用 X 继续",
        xFailed         : "X 登录失败",
        sendCode        : "发送验证码",
        resendCode      : "重新发送",
        resendIn        : "%s 秒后重新发送",
        verifyButton    : "验证",
        selectModel     : "选择模型",
        emptyTitle      : "开始对话",
        emptySubtitle   : "选择下方模型，然后发送第一条消息。",
        messageHint     : "有什么想问的？",
        send            : "发送",
        statsTitle      : "响应详情",
        statsModel      : "模型",
        statsInput      : "输入 Token",
        statsOutput     : "输出 Token",
        statsTotalTokens : "总 Token",
        statsTotalCost  : "总费用",
        close           : "关闭",
        copyReply       : "复制回复",
        emailRequired   : "请输入邮箱",
        sendingCode     : "正在发送验证码…",
        codeSentTo      : "验证码已发送至 %s。",
        sendFailed      : "发送验证码失败。",
        enterCode       : "请输入邮件中的验证码。",
        verifying       : "正在验证…",
        verifyFailed    : "验证失败。",
        badResponse     : "服务器返回的数据格式异常。",
        requestFailed   : "出错了，请稍后重试。",
        historyTitle    : "历史",
        historyEmpty    : "暂无历史记录。",
        historyUntitled : "未命名",
        historyLoadFailed : "加载历史记录失败。",
        historyDeleteTitle : "删除该会话？",
        historyDeleteMessage : "该会话将被永久删除。",
        delete          : "删除",
        retry           : "重试",
        back            : "返回"
    },
    ja: {
        settings        : "設定",
        language        : "言語",
        fontSize        : "文字サイズ",
        fontSmaller     : "最小",
        fontSmall       : "小",
        fontNormal      : "標準",
        fontLarge       : "大",
        fontLarger      : "最大",
        backend         : "バックエンド",
        backendUrl      : "バックエンド URL",
        backendSubtitle : "このアプリを Mirobody バックエンドのインスタンスに接続します。",
        backendHint     : "空欄の場合はこのサーバーを使用します。",
        invalidUrl      : "有効な http(s) URL ではありません",
        save            : "保存",
        cancel          : "キャンセル",
        about           : "バージョン情報",
        version         : "バージョン %s",
        signOut         : "ログアウト",
        loginTitle      : "ログイン",
        loginSubtitle   : "ワンタイムコードをメールで送信します。",
        authOr          : "または",
        continueWithGoogle : "Google で続行",
        googleFailed    : "Google サインインに失敗しました",
        continueWithWeChat : "WeChat で続行",
        wechatFailed    : "WeChat サインインに失敗しました",
        continueWithApple : "Apple で続行",
        appleFailed     : "Apple サインインに失敗しました",
        continueWithGitHub : "GitHub で続行",
        githubFailed    : "GitHub サインインに失敗しました",
        continueWithX   : "X で続行",
        xFailed         : "X サインインに失敗しました",
        sendCode        : "コードを送信",
        resendCode      : "コードを再送信",
        resendIn        : "%s 秒後に再送信",
        verifyButton    : "認証",
        selectModel     : "モデルを選択",
        emptyTitle      : "会話を始めましょう",
        emptySubtitle   : "下でモデルを選んで、最初のメッセージを送信してください。",
        messageHint     : "何でも質問してください",
        send            : "送信",
        statsTitle      : "応答の詳細",
        statsModel      : "モデル",
        statsInput      : "入力トークン",
        statsOutput     : "出力トークン",
        statsTotalTokens : "合計トークン",
        statsTotalCost  : "合計コスト",
        close           : "閉じる",
        copyReply       : "返信をコピー",
        emailRequired   : "メールアドレスを入力してください",
        sendingCode     : "コードを送信中…",
        codeSentTo      : "%s にコードを送信しました。",
        sendFailed      : "コードの送信に失敗しました。",
        enterCode       : "メールに記載のコードを入力してください。",
        verifying       : "認証中…",
        verifyFailed    : "認証に失敗しました。",
        badResponse     : "サーバーからの応答形式が予期しないものです。",
        requestFailed   : "エラーが発生しました。",
        historyTitle    : "履歴",
        historyEmpty    : "履歴はまだありません。",
        historyUntitled : "無題",
        historyLoadFailed : "履歴の読み込みに失敗しました。",
        historyDeleteTitle : "この会話を削除しますか？",
        historyDeleteMessage : "この会話は完全に削除されます。",
        delete          : "削除",
        retry           : "再試行",
        back            : "戻る"
    },
    ko: {
        settings        : "설정",
        language        : "언어",
        fontSize        : "글자 크기",
        fontSmaller     : "아주 작게",
        fontSmall       : "작게",
        fontNormal      : "보통",
        fontLarge       : "크게",
        fontLarger      : "아주 크게",
        backend         : "백엔드",
        backendUrl      : "백엔드 URL",
        backendSubtitle : "이 앱을 Mirobody 백엔드 인스턴스로 연결하세요.",
        backendHint     : "비워 두면 현재 서버를 사용합니다.",
        invalidUrl      : "유효한 http(s) URL이 아닙니다",
        save            : "저장",
        cancel          : "취소",
        about           : "정보",
        version         : "버전 %s",
        signOut         : "로그아웃",
        loginTitle      : "로그인",
        loginSubtitle   : "일회용 코드를 이메일로 보내드립니다.",
        authOr          : "또는",
        continueWithGoogle : "Google로 계속",
        googleFailed    : "Google 로그인 실패",
        continueWithWeChat : "WeChat로 계속",
        wechatFailed    : "WeChat 로그인 실패",
        continueWithApple : "Apple로 계속",
        appleFailed     : "Apple 로그인 실패",
        continueWithGitHub : "GitHub로 계속",
        githubFailed    : "GitHub 로그인 실패",
        continueWithX   : "X로 계속",
        xFailed         : "X 로그인 실패",
        sendCode        : "코드 보내기",
        resendCode      : "코드 다시 보내기",
        resendIn        : "%s초 후 다시 보내기",
        verifyButton    : "확인",
        selectModel     : "모델 선택",
        emptyTitle      : "대화 시작하기",
        emptySubtitle   : "아래에서 모델을 선택한 후 첫 메시지를 보내세요.",
        messageHint     : "무엇이든 물어보세요",
        send            : "보내기",
        statsTitle      : "응답 세부정보",
        statsModel      : "모델",
        statsInput      : "입력 토큰",
        statsOutput     : "출력 토큰",
        statsTotalTokens : "전체 토큰",
        statsTotalCost  : "총 비용",
        close           : "닫기",
        copyReply       : "답변 복사",
        emailRequired   : "이메일을 입력하세요",
        sendingCode     : "코드 보내는 중…",
        codeSentTo      : "%s 로 코드를 보냈습니다.",
        sendFailed      : "코드 전송에 실패했습니다.",
        enterCode       : "이메일로 받은 코드를 입력하세요.",
        verifying       : "확인 중…",
        verifyFailed    : "인증에 실패했습니다.",
        badResponse     : "서버 응답 형식이 올바르지 않습니다.",
        requestFailed   : "문제가 발생했습니다.",
        historyTitle    : "기록",
        historyEmpty    : "기록이 없습니다.",
        historyUntitled : "제목 없음",
        historyLoadFailed : "기록을 불러오지 못했습니다.",
        historyDeleteTitle : "이 대화를 삭제하시겠습니까?",
        historyDeleteMessage : "이 대화는 영구적으로 삭제됩니다.",
        delete          : "삭제",
        retry           : "다시 시도",
        back            : "뒤로"
    },
    fr: {
        settings        : "Paramètres",
        language        : "Langue",
        fontSize        : "Taille du texte",
        fontSmaller     : "Très petit",
        fontSmall       : "Petit",
        fontNormal      : "Normal",
        fontLarge       : "Grand",
        fontLarger      : "Très grand",
        backend         : "Serveur",
        backendUrl      : "URL du serveur",
        backendSubtitle : "Connectez cette application à une instance de serveur Mirobody.",
        backendHint     : "Laissez vide pour utiliser ce serveur.",
        invalidUrl      : "URL http(s) invalide",
        save            : "Enregistrer",
        cancel          : "Annuler",
        about           : "À propos",
        version         : "Version %s",
        signOut         : "Se déconnecter",
        loginTitle      : "Se connecter",
        loginSubtitle   : "Nous vous enverrons un code à usage unique par e-mail.",
        authOr          : "ou",
        continueWithGoogle : "Continuer avec Google",
        googleFailed    : "Échec de la connexion Google",
        continueWithWeChat : "Continuer avec WeChat",
        wechatFailed    : "Échec de la connexion WeChat",
        continueWithApple : "Continuer avec Apple",
        appleFailed     : "Échec de la connexion Apple",
        continueWithGitHub : "Continuer avec GitHub",
        githubFailed    : "Échec de la connexion GitHub",
        continueWithX   : "Continuer avec X",
        xFailed         : "Échec de la connexion X",
        sendCode        : "Envoyer le code",
        resendCode      : "Renvoyer le code",
        resendIn        : "Renvoyer dans %s s",
        verifyButton    : "Vérifier",
        selectModel     : "Choisir un modèle",
        emptyTitle      : "Démarrer une conversation",
        emptySubtitle   : "Choisissez un modèle ci-dessous, puis envoyez votre premier message.",
        messageHint     : "Posez n'importe quelle question",
        send            : "Envoyer",
        statsTitle      : "Détails de la réponse",
        statsModel      : "Modèle",
        statsInput      : "Tokens d'entrée",
        statsOutput     : "Tokens de sortie",
        statsTotalTokens : "Total des tokens",
        statsTotalCost  : "Coût total",
        close           : "Fermer",
        copyReply       : "Copier la réponse",
        emailRequired   : "L'e-mail est requis",
        sendingCode     : "Envoi du code…",
        codeSentTo      : "Code envoyé à %s.",
        sendFailed      : "Échec de l'envoi du code.",
        enterCode       : "Saisissez le code reçu par e-mail.",
        verifying       : "Vérification…",
        verifyFailed    : "Échec de la vérification.",
        badResponse     : "Réponse inattendue du serveur.",
        requestFailed   : "Une erreur est survenue.",
        historyTitle    : "Historique",
        historyEmpty    : "Aucun historique.",
        historyUntitled : "Sans titre",
        historyLoadFailed : "Échec du chargement de l'historique.",
        historyDeleteTitle : "Supprimer cette conversation ?",
        historyDeleteMessage : "Cette conversation sera définitivement supprimée.",
        delete          : "Supprimer",
        retry           : "Réessayer",
        back            : "Retour"
    },
    de: {
        settings        : "Einstellungen",
        language        : "Sprache",
        fontSize        : "Schriftgröße",
        fontSmaller     : "Sehr klein",
        fontSmall       : "Klein",
        fontNormal      : "Normal",
        fontLarge       : "Groß",
        fontLarger      : "Sehr groß",
        backend         : "Backend",
        backendUrl      : "Backend-URL",
        backendSubtitle : "Verbinden Sie diese App mit einer Mirobody-Backend-Instanz.",
        backendHint     : "Leer lassen, um diesen Server zu verwenden.",
        invalidUrl      : "Keine gültige http(s)-URL",
        save            : "Speichern",
        cancel          : "Abbrechen",
        about           : "Über",
        version         : "Version %s",
        signOut         : "Abmelden",
        loginTitle      : "Anmelden",
        loginSubtitle   : "Wir senden Ihnen einen Einmalcode per E-Mail.",
        authOr          : "oder",
        continueWithGoogle : "Mit Google fortfahren",
        googleFailed    : "Google-Anmeldung fehlgeschlagen",
        continueWithWeChat : "Mit WeChat fortfahren",
        wechatFailed    : "WeChat-Anmeldung fehlgeschlagen",
        continueWithApple : "Mit Apple fortfahren",
        appleFailed     : "Apple-Anmeldung fehlgeschlagen",
        continueWithGitHub : "Mit GitHub fortfahren",
        githubFailed    : "GitHub-Anmeldung fehlgeschlagen",
        continueWithX   : "Mit X fortfahren",
        xFailed         : "X-Anmeldung fehlgeschlagen",
        sendCode        : "Code senden",
        resendCode      : "Code erneut senden",
        resendIn        : "Erneut senden in %s s",
        verifyButton    : "Bestätigen",
        selectModel     : "Modell wählen",
        emptyTitle      : "Konversation beginnen",
        emptySubtitle   : "Wählen Sie unten ein Modell und senden Sie Ihre erste Nachricht.",
        messageHint     : "Beliebige Frage stellen",
        send            : "Senden",
        statsTitle      : "Antwortdetails",
        statsModel      : "Modell",
        statsInput      : "Eingabe-Tokens",
        statsOutput     : "Ausgabe-Tokens",
        statsTotalTokens : "Tokens insgesamt",
        statsTotalCost  : "Gesamtkosten",
        close           : "Schließen",
        copyReply       : "Antwort kopieren",
        emailRequired   : "E-Mail erforderlich",
        sendingCode     : "Code wird gesendet…",
        codeSentTo      : "Code an %s gesendet.",
        sendFailed      : "Code konnte nicht gesendet werden.",
        enterCode       : "Geben Sie den Code aus Ihrer E-Mail ein.",
        verifying       : "Wird bestätigt…",
        verifyFailed    : "Bestätigung fehlgeschlagen.",
        badResponse     : "Unerwartete Antwort vom Server.",
        requestFailed   : "Etwas ist schiefgegangen.",
        historyTitle    : "Verlauf",
        historyEmpty    : "Noch kein Verlauf.",
        historyUntitled : "Ohne Titel",
        historyLoadFailed : "Verlauf konnte nicht geladen werden.",
        historyDeleteTitle : "Konversation löschen?",
        historyDeleteMessage : "Diese Konversation wird endgültig entfernt.",
        delete          : "Löschen",
        retry           : "Erneut versuchen",
        back            : "Zurück"
    },
    ru: {
        settings        : "Настройки",
        language        : "Язык",
        fontSize        : "Размер шрифта",
        fontSmaller     : "Очень мелкий",
        fontSmall       : "Мелкий",
        fontNormal      : "Обычный",
        fontLarge       : "Крупный",
        fontLarger      : "Очень крупный",
        backend         : "Сервер",
        backendUrl      : "URL сервера",
        backendSubtitle : "Укажите экземпляр сервера Mirobody для этого приложения.",
        backendHint     : "Оставьте пустым, чтобы использовать этот сервер.",
        invalidUrl      : "Неверный http(s) URL",
        save            : "Сохранить",
        cancel          : "Отмена",
        about           : "О приложении",
        version         : "Версия %s",
        signOut         : "Выйти",
        loginTitle      : "Войти",
        loginSubtitle   : "Мы отправим вам одноразовый код по электронной почте.",
        authOr          : "или",
        continueWithGoogle : "Продолжить через Google",
        googleFailed    : "Не удалось войти через Google",
        continueWithWeChat : "Продолжить через WeChat",
        wechatFailed    : "Не удалось войти через WeChat",
        continueWithApple : "Продолжить через Apple",
        appleFailed     : "Не удалось войти через Apple",
        continueWithGitHub : "Продолжить через GitHub",
        githubFailed    : "Не удалось войти через GitHub",
        continueWithX   : "Продолжить через X",
        xFailed         : "Не удалось войти через X",
        sendCode        : "Отправить код",
        resendCode      : "Отправить заново",
        resendIn        : "Повтор через %s сек",
        verifyButton    : "Подтвердить",
        selectModel     : "Выбрать модель",
        emptyTitle      : "Начните разговор",
        emptySubtitle   : "Выберите модель ниже и отправьте первое сообщение.",
        messageHint     : "Спросите о чём угодно",
        send            : "Отправить",
        statsTitle      : "Детали ответа",
        statsModel      : "Модель",
        statsInput      : "Входные токены",
        statsOutput     : "Выходные токены",
        statsTotalTokens : "Всего токенов",
        statsTotalCost  : "Общая стоимость",
        close           : "Закрыть",
        copyReply       : "Копировать ответ",
        emailRequired   : "Введите эл. почту",
        sendingCode     : "Отправка кода…",
        codeSentTo      : "Код отправлен на %s.",
        sendFailed      : "Не удалось отправить код.",
        enterCode       : "Введите код из письма.",
        verifying       : "Проверка…",
        verifyFailed    : "Не удалось подтвердить.",
        badResponse     : "Неожиданный ответ от сервера.",
        requestFailed   : "Что-то пошло не так.",
        historyTitle    : "История",
        historyEmpty    : "История пуста.",
        historyUntitled : "Без названия",
        historyLoadFailed : "Не удалось загрузить историю.",
        historyDeleteTitle : "Удалить эту переписку?",
        historyDeleteMessage : "Эта переписка будет удалена навсегда.",
        delete          : "Удалить",
        retry           : "Повторить",
        back            : "Назад"
    },
    es: {
        settings        : "Ajustes",
        language        : "Idioma",
        fontSize        : "Tamaño de fuente",
        fontSmaller     : "Muy pequeño",
        fontSmall       : "Pequeño",
        fontNormal      : "Normal",
        fontLarge       : "Grande",
        fontLarger      : "Muy grande",
        backend         : "Servidor",
        backendUrl      : "URL del servidor",
        backendSubtitle : "Apunta esta app a una instancia del servidor Mirobody.",
        backendHint     : "Déjalo en blanco para usar este servidor.",
        invalidUrl      : "URL http(s) no válida",
        save            : "Guardar",
        cancel          : "Cancelar",
        about           : "Acerca de",
        version         : "Versión %s",
        signOut         : "Cerrar sesión",
        loginTitle      : "Iniciar sesión",
        loginSubtitle   : "Te enviaremos un código de un solo uso por correo.",
        authOr          : "o",
        continueWithGoogle : "Continuar con Google",
        googleFailed    : "Error al iniciar sesión con Google",
        continueWithWeChat : "Continuar con WeChat",
        wechatFailed    : "Error al iniciar sesión con WeChat",
        continueWithApple : "Continuar con Apple",
        appleFailed     : "Error al iniciar sesión con Apple",
        continueWithGitHub : "Continuar con GitHub",
        githubFailed    : "Error al iniciar sesión con GitHub",
        continueWithX   : "Continuar con X",
        xFailed         : "Error al iniciar sesión con X",
        sendCode        : "Enviar código",
        resendCode      : "Reenviar código",
        resendIn        : "Reenviar en %s s",
        verifyButton    : "Verificar",
        selectModel     : "Elegir modelo",
        emptyTitle      : "Iniciar una conversación",
        emptySubtitle   : "Elige un modelo abajo y envía tu primer mensaje.",
        messageHint     : "Pregunta lo que quieras",
        send            : "Enviar",
        statsTitle      : "Detalles de la respuesta",
        statsModel      : "Modelo",
        statsInput      : "Tokens de entrada",
        statsOutput     : "Tokens de salida",
        statsTotalTokens : "Tokens totales",
        statsTotalCost  : "Coste total",
        close           : "Cerrar",
        copyReply       : "Copiar respuesta",
        emailRequired   : "Se requiere correo",
        sendingCode     : "Enviando código…",
        codeSentTo      : "Código enviado a %s.",
        sendFailed      : "No se pudo enviar el código.",
        enterCode       : "Introduce el código de tu correo.",
        verifying       : "Verificando…",
        verifyFailed    : "Error de verificación.",
        badResponse     : "Respuesta inesperada del servidor.",
        requestFailed   : "Algo salió mal.",
        historyTitle    : "Historial",
        historyEmpty    : "Sin historial todavía.",
        historyUntitled : "Sin título",
        historyLoadFailed : "No se pudo cargar el historial.",
        historyDeleteTitle : "¿Eliminar esta conversación?",
        historyDeleteMessage : "Esta conversación se eliminará permanentemente.",
        delete          : "Eliminar",
        retry           : "Reintentar",
        back            : "Atrás"
    },
    ar: {
        settings        : "الإعدادات",
        language        : "اللغة",
        fontSize        : "حجم الخط",
        fontSmaller     : "أصغر",
        fontSmall       : "صغير",
        fontNormal      : "عادي",
        fontLarge       : "كبير",
        fontLarger      : "أكبر",
        backend         : "الخادم",
        backendUrl      : "عنوان الخادم",
        backendSubtitle : "وجّه هذا التطبيق إلى خادم Mirobody.",
        backendHint     : "اتركه فارغًا لاستخدام هذا الخادم.",
        invalidUrl      : "عنوان http(s) غير صالح",
        save            : "حفظ",
        cancel          : "إلغاء",
        about           : "حول",
        version         : "الإصدار %s",
        signOut         : "تسجيل الخروج",
        loginTitle      : "تسجيل الدخول",
        loginSubtitle   : "سنرسل إليك رمزًا لمرة واحدة عبر البريد الإلكتروني.",
        authOr          : "أو",
        continueWithGoogle : "المتابعة باستخدام Google",
        googleFailed    : "فشل تسجيل الدخول عبر Google",
        continueWithWeChat : "المتابعة باستخدام WeChat",
        wechatFailed    : "فشل تسجيل الدخول عبر WeChat",
        continueWithApple : "المتابعة باستخدام Apple",
        appleFailed     : "فشل تسجيل الدخول عبر Apple",
        continueWithGitHub : "المتابعة باستخدام GitHub",
        githubFailed    : "فشل تسجيل الدخول عبر GitHub",
        continueWithX   : "المتابعة باستخدام X",
        xFailed         : "فشل تسجيل الدخول عبر X",
        sendCode        : "إرسال الرمز",
        resendCode      : "إعادة إرسال الرمز",
        resendIn        : "إعادة الإرسال خلال %s ثانية",
        verifyButton    : "تحقق",
        selectModel     : "اختر النموذج",
        emptyTitle      : "ابدأ محادثة",
        emptySubtitle   : "اختر نموذجًا بالأسفل ثم أرسل رسالتك الأولى.",
        messageHint     : "اسأل عن أي شيء",
        send            : "إرسال",
        statsTitle      : "تفاصيل الرد",
        statsModel      : "النموذج",
        statsInput      : "رموز الإدخال",
        statsOutput     : "رموز الإخراج",
        statsTotalTokens : "إجمالي الرموز",
        statsTotalCost  : "التكلفة الإجمالية",
        close           : "إغلاق",
        copyReply       : "نسخ الرد",
        emailRequired   : "البريد الإلكتروني مطلوب",
        sendingCode     : "جارٍ إرسال الرمز…",
        codeSentTo      : "تم إرسال الرمز إلى %s.",
        sendFailed      : "فشل إرسال الرمز.",
        enterCode       : "أدخل الرمز من بريدك الإلكتروني.",
        verifying       : "جارٍ التحقق…",
        verifyFailed    : "فشل التحقق.",
        badResponse     : "استجابة غير متوقعة من الخادم.",
        requestFailed   : "حدث خطأ ما.",
        historyTitle    : "السجل",
        historyEmpty    : "لا يوجد سجل بعد.",
        historyUntitled : "بدون عنوان",
        historyLoadFailed : "فشل تحميل السجل.",
        historyDeleteTitle : "حذف المحادثة؟",
        historyDeleteMessage : "ستُحذف هذه المحادثة نهائيًا.",
        delete          : "حذف",
        retry           : "إعادة المحاولة",
        back            : "رجوع"
    },
    he: {
        settings        : "הגדרות",
        language        : "שפה",
        fontSize        : "גודל גופן",
        fontSmaller     : "קטן מאוד",
        fontSmall       : "קטן",
        fontNormal      : "רגיל",
        fontLarge       : "גדול",
        fontLarger      : "גדול מאוד",
        backend         : "שרת",
        backendUrl      : "כתובת השרת",
        backendSubtitle : "הפנה אפליקציה זו למופע שרת Mirobody.",
        backendHint     : "השאר ריק כדי להשתמש בשרת זה.",
        invalidUrl      : "כתובת http(s) לא תקינה",
        save            : "שמירה",
        cancel          : "ביטול",
        about           : "אודות",
        version         : "גרסה %s",
        signOut         : "התנתקות",
        loginTitle      : "התחברות",
        loginSubtitle   : "נשלח לך קוד חד-פעמי באימייל.",
        authOr          : "או",
        continueWithGoogle : "המשך עם Google",
        googleFailed    : "ההתחברות עם Google נכשלה",
        continueWithWeChat : "המשך עם WeChat",
        wechatFailed    : "ההתחברות עם WeChat נכשלה",
        continueWithApple : "המשך עם Apple",
        appleFailed     : "ההתחברות עם Apple נכשלה",
        continueWithGitHub : "המשך עם GitHub",
        githubFailed    : "ההתחברות עם GitHub נכשלה",
        continueWithX   : "המשך עם X",
        xFailed         : "ההתחברות עם X נכשלה",
        sendCode        : "שליחת קוד",
        resendCode      : "שליחת קוד מחדש",
        resendIn        : "שליחה מחדש בעוד %s שניות",
        verifyButton    : "אימות",
        selectModel     : "בחר מודל",
        emptyTitle      : "התחל שיחה",
        emptySubtitle   : "בחר מודל למטה ושלח את ההודעה הראשונה שלך.",
        messageHint     : "שאל כל דבר",
        send            : "שליחה",
        statsTitle      : "פרטי התשובה",
        statsModel      : "מודל",
        statsInput      : "אסימוני קלט",
        statsOutput     : "אסימוני פלט",
        statsTotalTokens : "סך האסימונים",
        statsTotalCost  : "עלות כוללת",
        close           : "סגירה",
        copyReply       : "העתק תשובה",
        emailRequired   : "נדרש אימייל",
        sendingCode     : "שולח קוד…",
        codeSentTo      : "הקוד נשלח אל %s.",
        sendFailed      : "שליחת הקוד נכשלה.",
        enterCode       : "הזן את הקוד מהאימייל שלך.",
        verifying       : "מאמת…",
        verifyFailed    : "האימות נכשל.",
        badResponse     : "תגובה לא צפויה מהשרת.",
        requestFailed   : "משהו השתבש.",
        historyTitle    : "היסטוריה",
        historyEmpty    : "אין היסטוריה עדיין.",
        historyUntitled : "ללא כותרת",
        historyLoadFailed : "טעינת ההיסטוריה נכשלה.",
        historyDeleteTitle : "למחוק את השיחה?",
        historyDeleteMessage : "שיחה זו תימחק לצמיתות.",
        delete          : "מחיקה",
        retry           : "נסה שוב",
        back            : "חזרה"
    }
};

// Look up a key in `lang`, falling back to English then to the key itself. A
// single "%s" placeholder is replaced when `arg` is provided. Mirrors i18n.t().
function tr(lang, key, arg) {
    var table = STRINGS[lang] || STRINGS.en;
    var s = table[key];
    if (s === undefined) { s = STRINGS.en[key]; }
    if (s === undefined) { return key; }
    if (arg !== undefined && arg !== null) { s = s.replace("%s", arg); }
    return s;
}