#include "fhir/units/tokens.hpp"

// Verbatim C++ port of mirobody/indicator/fhir/units/tokens.py. UTF-8 source;
// the build adds /utf-8 on MSVC so the multibyte literals encode correctly.
// Keep the entries — keys (canonical UCUM) and variant lists — in sync with the
// Python tables, in the same order (the inverted lookup is order-sensitive).

namespace mirobody { namespace fhir { namespace units {

const TokenTable& morphemes() {
    static const TokenTable t = {
        {"", {"Schläge", "latidos", "latido", "lat", "battement", "battements", "bat", "個", "拍", "回", "개", "회", "박동", "ударов", "уд", "п", "з", "поле", "зрения", "个", "次"}},
        {"%", {"Prozent", "por ciento", "porcentaje", "porciento", "pour cent", "pourcent", "pourcentage", "パーセント", "퍼센트", "백분율", "процент", "процентов", "百分点", "百分比", "百分之", "百分", "百分點"}},
        {"/", {"pro", "per", "por", "/", "par", "毎", "매", "당", "на", "в", "每"}},
        {"/[HPF]", {"高倍視野", "強拡大", "1視野", "고배율시야", "고배율", "в поле зрения", "п/з", "每高倍视野", "高倍视野", "每高倍視野"}},
        {"/[LPF]", {"弱拡大", "저배율시야", "저배율", "每低倍视野", "低倍视野", "每低倍視野", "低倍視野"}},
        {"/d", {"일당"}},
        {"/h", {"시간당"}},
        {"/min", {"latidos por minuto", "latidos/min", "battements par minute", "battements/min", "분당"}},
        {"/s", {"초당"}},
        {"1", {"Pro Mille", "Verhältnis", "proporción", "mille", "rapport", "比率", "比", "비율", "비", "отношение"}},
        {"10*12/L", {"10¹²/л", "10^12/л", "×10¹²/л", "10*12/л"}},
        {"10*9/L", {"10⁹/л", "10^9/л", "×10⁹/л", "10*9/л"}},
        {"L", {"Liter", "l", "litros", "litro", "litres", "litre", "リットル", "리터", "литр", "Л", "литре", "литры", "литров", "л", "公升", "升"}},
        {"U", {"Einheiten", "Einheit", "E", "unidades", "unidad", "unités", "unité", "単位", "단위", "Ед", "ед", "ЕД", "единица", "единиц", "единицы", "单位", "單位"}},
        {"[H2O]", {"Wassersäule"}},
        {"[Hg]", {"Quecksilbersäule", "汞柱", "水银柱", "水銀柱"}},
        {"[IU]", {"Internationale Einheiten", "Internationale Einheit", "IE", "unidades internacionales", "unidad internacional", "UI", "unités internationales", "unité internationale", "国際単位", "국제단위", "международная единица", "международные единицы", "международных единиц", "МЕ", "ме", "国际单位", "國際單位"}},
        {"a", {"年", "년", "年間", "году", "год", "лет", "года", "Jahr", "Jahre", "année", "années", "an", "ans", "año", "años", "yr", "yrs"}},
        {"cL", {"Zentiliter"}},
        {"cm", {"Zentimeter", "centímetros", "centímetro", "centimètres", "centimètre", "センチメートル", "센티미터", "сантиметр", "см", "厘米", "公分", "寸"}},
        {"cm3", {"mètre cube"}},
        {"cm[H2O]", {"centímetros de agua", "centimètres d'eau", "センチメートル水柱", "센티미터수주", "см вод.ст.", "см вод. ст.", "厘米水柱", "釐米水柱"}},
        {"d", {"Tag", "Tage", "Tagen", "días", "día", "jours", "jour", "24時間", "日", "24시간", "일", "24часа", "24часов", "24ч", "сутки", "сутка", "сут", "суток", "д", "24小时", "天", "24小時"}},
        {"dL", {"Deziliter", "dl", "decilitros", "decilitro", "décilitres", "décilitre", "デシリットル", "데시리터", "децилитр", "дл", "Дл", "分升"}},
        {"fL", {"Femtoliter", "femtolitros", "femtolitro", "femtolitres", "femtolitre", "フェムトリットル", "펨토리터", "фл", "飞升"}},
        {"fg", {"Femtogramm", "フェムトグラム", "펨토그램", "飞克"}},
        {"fmol", {"Femtomol", "femtomoles", "femtomol", "femtomole", "フェムトモル", "펨토몰", "фемтомоль", "фмоль", "飞摩尔", "飛摩爾"}},
        {"g", {"Gramm", "gramos", "gramo", "grammes", "gramme", "グラム", "그램", "грамм", "грамма", "граммов", "г", "克"}},
        {"h", {"Stunden", "Stunde", "Std", "horas", "hora", "hr", "heures", "heure", "時間", "時", "시간", "시", "часов", "часы", "час", "ч", "小时", "时", "小時"}},
        {"kU", {"kE", "キロ単位", "킬로단위", "кЕд", "千单位", "千單位"}},
        {"k[IU]", {"kIE", "kUI", "キロ国際単位", "킬로국제단위", "кМЕ", "千国际单位", "千國際單位"}},
        {"kg", {"Kilogramm", "kilogramos", "kilogramo", "kilogrammes", "kilogramme", "キログラム", "킬로그램", "килограмм", "кг", "公斤", "千克"}},
        {"kg/m2", {"кг/м²", "кг/м2"}},
        {"km", {"公里", "千米"}},
        {"m", {"Meter", "metros", "metro", "mètres", "mètre", "メートル", "미터", "метр", "м", "米"}},
        {"m2", {"Quadratmeter", "metro cuadrado", "mètre carré", "mètres carrés", "平方メートル", "제곱미터", "м²", "м2", "平方米"}},
        {"mL", {"Milliliter", "ml", "mililitros", "mililitro", "millilitres", "millilitre", "ミリリットル", "밀리리터", "миллилитр", "мл", "мЛ", "毫升"}},
        {"mU", {"mE", "ミリ単位", "밀리단위", "мЕд", "毫单位", "毫單位"}},
        {"m[IU]", {"mIE", "mUI", "ミリ国際単位", "밀리국제단위", "мМЕ", "毫国际单位", "毫國際單位"}},
        {"meq", {"Milliäquivalent", "mval", "miliequivalentes", "miliequivalente", "milliéquivalents", "milliéquivalent", "ミリ当量", "밀리당량", "миллиэквивалент", "мэкв", "毫当量", "毫當量"}},
        {"mg", {"Milligramm", "miligramos", "miligramo", "milligrammes", "milligramme", "ミリグラム", "밀리그램", "миллиграмм", "мг", "毫克"}},
        {"mg/dL", {"мг%"}},
        {"min", {"Minuten", "Minute", "Min", "minutos", "minuto", "minutes", "minute", "mn", "分", "분", "минуты", "минут", "минута", "минуту", "мин", "分钟", "分鐘"}},
        {"mm", {"Millimeter", "milímetros", "milímetro", "millimètres", "millimètre", "ミリメートル", "밀리미터", "миллиметр", "мм", "毫米"}},
        {"mm[Hg]", {"milímetros de mercurio", "millimètres de mercure", "ミリメートル水銀柱", "水銀柱ミリメートル", "밀리미터수은주", "수은주밀리미터", "мм рт.ст.", "мм рт. ст.", "мм рт ст", "мм Hg", "ммHg", "миллиметров ртутного столба", "миллиметра ртутного столба", "миллиметр ртутного столба", "毫米汞柱"}},
        {"mmol", {"Millimol", "milimoles", "milimol", "millimoles", "millimole", "mmoles", "mmole", "ミリモル", "밀리몰", "миллимоль", "ммоль", "毫摩尔", "毫摩爾"}},
        {"mo", {"月", "달", "개월", "ヶ月", "か月", "месяц", "месяца", "месяцев", "Monat", "Monate", "Monaten", "mois", "mes", "meses"}},
        {"mol", {"Mol", "moles", "mole", "mol", "モル", "몰", "моль", "摩尔", "摩爾"}},
        {"mosm", {"Milliosmol", "mosmol", "miliosmoles", "miliosmol", "milliosmoles", "milliosmole", "ミリオスモル", "밀리오스몰", "миллиосмоль", "мосм", "毫渗摩尔", "毫滲摩爾"}},
        {"nL", {"Nanoliter", "nanolitros", "nanolitro", "nanolitres", "nanolitre", "ナノリットル", "나노리터", "нанолитр", "纳升", "奈升"}},
        {"ng", {"Nanogramm", "nanogramos", "nanogramo", "nanogrammes", "nanogramme", "ナノグラム", "나노그램", "нанограмм", "нг", "наног", "纳克", "奈克"}},
        {"nmol", {"Nanomol", "nanomoles", "nanomol", "nanomole", "ナノモル", "나노몰", "наномоль", "нмоль", "纳摩尔", "奈摩爾"}},
        {"osmol", {"オスモル", "오스몰", "осмоль", "渗摩尔", "滲摩爾"}},
        {"pg", {"Pikogramm", "picogramos", "picogramo", "picogrammes", "picogramme", "ピコグラム", "피코그램", "пикограмм", "пг", "皮克"}},
        {"pmol", {"Pikomol", "picomoles", "picomol", "picomole", "ピコモル", "피코몰", "пикомоль", "пмоль", "皮摩尔", "皮摩爾"}},
        {"s", {"Sekunden", "Sekunde", "Sek", "segundos", "segundo", "seg", "secondes", "seconde", "sec", "秒", "초", "секунды", "секунд", "секунда", "секунду", "сек", "с"}},
        {"uL", {"Mikroliter", "ul", "microlitros", "microlitro", "microlitres", "microlitre", "マイクロリットル", "마이크로리터", "микролитр", "мкл", "мкЛ", "微升"}},
        {"ug", {"Mikrogramm", "microgramos", "microgramo", "microgrammes", "microgramme", "マイクログラム", "마이크로그램", "микрограмм", "мкг", "微克"}},
        {"um", {"Mikrometer", "micrómetros", "micrómetro", "micromètres", "micromètre", "マイクロメートル", "마이크로미터", "микрометр", "微米"}},
        {"umol", {"Mikromol", "micromoles", "micromol", "micromole", "マイクロモル", "마이크로몰", "микромоль", "мкмоль", "微摩尔", "微摩爾"}},
        {"wk", {"Woche", "Wochen", "semanas", "semana", "semaines", "semaine", "週", "週間", "주", "неделя", "недели", "нед", "недель", "周"}},
    };
    return t;
}

const TokenTable& aliases() {
    static const TokenTable t = {
        {"%", {"percent", "pct", "PCT", "spo2", "SpO2"}},
        // Bare "HPF"/"LPF" are not UCUM units; "[HPF]"/"[LPF]" are. Labs write
        // the unbracketed form, so it is an alias, never a canonical.
        {"/[HPF]", {"/HPF", "/hpf", "HPF", "p/HPF"}},
        {"/[LPF]", {"/LPF", "/lpf", "LPF"}},
        {"/min", {"/min", "per min", "bpm", "beats/min", "breaths/min", "count/min", "cnt/min"}},
        {"/h", {"count/hour", "count/hr", "cnt/h"}},
        {"1", {"ratio", "INR"}},
        {"10*12/L", {"10^12/L", "10^12/l", "×10^12/L", "×10¹²/L", "10¹²/L", "10E12/L", "10*12/l"}},
        {"10*9/L", {"10^9/L", "10^9/l", "x10^9/L", "×10^9/L", "×10⁹/L", "10⁹/L", "10E9/L", "10*9/l"}},
        {"cm", {"cm", "CM", "centimeters"}},
        {"cm[H2O]", {"cmH2O", "cm H2O"}},
        {"d", {"DAY", "day", "days"}},
        {"dL", {"DL", "dl"}},
        {"fL", {"fL", "fl", "femtoliter"}},
        {"g", {"g", "gm", "grams", "GM"}},
        {"J", {"Joule", "joule", "Joules", "joules", "焦耳", "ジュール", "주울", "джоуль"}},
        {"Ohm", {"ohm", "Ω", "Ом", "欧姆", "オーム", "옴"}},
        {"W", {"watt", "Watt", "watts", "Watts", "瓦", "瓦特", "ワット", "와트", "ватт"}},
        {"cal", {"gram calorie"}},
        {"h", {"hours", "hr", "HR", "hrs"}},
        {"kJ", {"kilojoule", "kilojoules", "千焦", "キロジュール"}},
        {"kW", {"kilowatt", "kilowatts", "千瓦", "キロワット"}},
        {"kcal", {"Cal", "Cals", "calorie", "calories", "Kcal", "KCAL", "kilocalorie", "kilocalories", "千卡", "大卡", "卡路里", "카로리", "칼로리", "킬로칼로리", "カロリー", "キロカロリー", "ккал", "Калории", "Kalorie", "Kalorien", "caloría", "calorías"}},
        {"kg", {"kg", "KG", "kilograms"}},
        {"kg/m2", {"kg/m^2", "kg/m²"}},
        {"m", {"m", "meters"}},
        {"m2", {"SQM", "m2", "m^2"}},
        {"mL", {"ML", "ml"}},
        {"mg", {"MG"}},
        {"mg/dL", {"mg/dl", "mg/DL", "MG/DL", "mgs/dl", "mgs/dL", "mg per dL", "mg/100mL", "mg%"}},
        {"min", {"minutes", "MIN"}},
        {"mm[Hg]", {"mmHg", "MMHG", "mm Hg", "Torr", "torr", "托"}},
        {"ng", {"NG"}},
        {"pg", {"pg", "PG"}},
        {"s", {"sec", "seconds", "SEC"}},
        {"uL", {"UL", "ul"}},
        {"ug", {"MCG", "mcg", "ug"}},
        {"wk", {"WK", "wk"}},
        {"/uL", {"/ul", "/μL", "/uL"}},
        {"10*3/uL", {"10^3/uL", "10^3/ul", "10^3/μL", "×10³/uL", "10³/uL", "10*3/ul", "K/uL", "k/uL"}},
        {"10*6/uL", {"10^6/uL", "10^6/μL", "×10⁶/uL", "10⁶/uL", "M/uL"}},
        {"Cel", {"°C", "degC", "celsius", "Celsius", "摄氏度", "攝氏度", "摄氏", "攝氏", "摂氏", "섭씨", "°С", "градус Цельсия", "градусов Цельсия", "Grad Celsius", "degrés Celsius", "grados Celsius"}},
        {"L/min", {"L per minute"}},
        {"U/L", {"U/L", "U/l", "u/L", "UNT/L"}},
        {"U", {"u", "unit", "units", "UNIT", "UNITS", "unt", "UNT"}},
        {"[IU]", {"IU", "iu", "iU", "I.U.", "I.U", "International Unit", "international unit", "IUs"}},
        {"{#}", {"count", "cnt", "counts", "次", "次数", "回数", "个数", "件", "カウント", "Anzahl", "veces"}},
        {"{steps}", {"steps", "step", "Steps", "STEPS", "步", "步数", "步數", "ステップ", "歩", "걸음", "шаг", "шагов", "Schritte", "Schritt", "pasos", "paso", "pas"}},
        {"{floors}", {"floors", "floor", "Floors", "层", "層", "楼层", "樓層", "フロア", "층", "этаж", "этажей", "Stockwerke", "étage", "pisos"}},
        {"{beats}", {"beats", "beat", "心跳", "搏", "拍数", "拍動"}},
        {"{breaths}", {"breaths", "breath", "呼吸次数", "呼吸数"}},
        {"{score}", {"score", "Score", "points", "pts", "分数", "分數", "得分", "점수", "スコア", "点数", "балл", "баллы", "баллов", "Punkte", "puntos", "puntuación"}},
        {"[IU]/L", {"IU/L", "IU/l", "iu/L", "IU per L"}},
        {"[IU]/mL", {"IU/mL", "IU/ml"}},
        {"[degF]", {"°F", "degF", "fahrenheit", "Fahrenheit", "华氏度", "華氏度", "华氏", "華氏", "華氏", "화씨", "°Ф", "градус Фаренгейта", "градусов Фаренгейта", "Grad Fahrenheit", "degrés Fahrenheit", "grados Fahrenheit"}},
        {"[diop]", {"diopter", "diopters", "D"}},
        {"[pH]", {"pH"}},
        {"[ppb]", {"ppb"}},
        {"[ppm]", {"ppm"}},
        {"[ft_us]", {"ft", "foot", "feet", "英尺", "尺", "フィート", "피트", "фут", "фута", "футов", "Fuß", "pied", "pieds", "pie", "pies"}},
        {"[in_us]", {"in", "inch", "inches", "英寸", "吋", "インチ", "인치", "дюйм", "дюйма", "дюймов", "Zoll", "pouce", "pouces", "pulgada", "pulgadas"}},
        {"[mi_us]", {"mi", "mile", "miles", "英里", "マイル", "마일", "миля", "мили", "миль", "Meile", "Meilen", "mille", "milles", "milla", "millas"}},
        {"[yd_us]", {"yd", "yard", "yards", "码", "碼", "ヤード", "야드", "ярд", "ярда", "ярдов", "verge", "yarda", "yardas"}},
        {"[lb_av]", {"lb", "lbs", "pound", "pounds", "磅", "英磅", "ポンド", "파운드", "фунт", "фунта", "фунтов", "Pfund", "livre", "livres", "libra", "libras"}},
        {"[oz_av]", {"oz", "ounce", "ounces", "盎司", "英两", "オンス", "온스", "унция", "унции", "унций", "Unze", "Unzen", "once", "onza", "onzas"}},
        {"[foz_us]", {"fl oz", "fl. oz", "floz", "fluid ounce", "液量盎司", "液体盎司"}},
        {"[cup_us]", {"cup", "cups", "杯"}},
        {"[pt_us]", {"pt", "pint", "pints", "品脱"}},
        {"[qt_us]", {"qt", "quart", "quarts", "夸脱"}},
        {"[gal_us]", {"gal", "gallon", "gallons", "加仑", "加侖", "ガロン", "갤런", "галлон", "Gallone", "galon", "galones", "galón"}},
        {"[tbs_us]", {"tbsp", "tablespoon", "tablespoons", "汤匙", "湯匙"}},
        {"[tsp_us]", {"tsp", "teaspoon", "teaspoons", "茶匙"}},
        {"cm2", {"SQCM", "cm^2"}},
        {"deg", {"degrees"}},
        {"fmol/L", {"fmol/l"}},
        {"g/L", {"g/l", "g/L"}},
        {"g/d", {"g/24h", "g/day"}},
        {"g/dL", {"g/dl", "g/DL", "G/DL", "g%", "gm/dL", "gm/dl"}},
        {"kU/L", {"kU/L"}},
        {"k[IU]/L", {"kIU/L"}},
        {"kat/L", {"katal/L"}},
        {"mCi", {"MCI", "mCi"}},
        {"mL/(24.h)", {"mL/24h"}},
        {"mL/min", {"mL per minute"}},
        {"mL/min/{1.73_m2}", {"mL/min/1.73m2", "mL/min/1.73 m2", "eGFR", "ml/min/{1.73_m2}", "ml/min/1.73m2", "mL/min/{1.73m2}", "ml/min/1.73 m2"}},
        {"mU/L", {"mU/L", "mU/l"}},
        {"mU/mL", {"mU/mL"}},
        {"m[IU]/L", {"mIU/L", "mIU/l"}},
        {"m[IU]/mL", {"mIU/mL", "mIU/ml"}},
        // Keep the milliequivalent dimensions apart: /L is a concentration,
        // /kg a content, /24h a rate. They used to share the meq/L canonical,
        // which reported a content and a rate as SCnc.
        {"meq/L", {"mEq/L", "mEq/l", "meq/l", "MEQ/L"}},
        {"meq/kg", {"mEq/kg"}},
        {"meq/d", {"mEq/24h", "mEq/24hr", "mEq/day", "meq/24h", "mEq/d"}},
        {"mg/L", {"mg/l"}},
        {"mg/d", {"mg/24h", "mg/24hr", "mg/day", "mg per day"}},
        {"mg/g", {"mg/g creatinine", "mg/g creat"}},
        {"mm2", {"mm^2"}},
        {"mmol/L", {"mmol/l", "MMOL/L", "mmol per L", "mmol/litre", "毫摩尔", "毫摩爾"}},
        {"mmol/d", {"mmol/24h", "mmol/24hr", "mmol per day"}},
        {"mmol/dL", {"mmol/dl"}},
        {"mol/L", {"mol/l"}},
        {"mol/dL", {"mol/dl"}},
        {"mosm/L", {"mOsm/L", "mosmol/L", "mosmol/l"}},
        {"mosm/kg", {"mOsm/kg", "mosmol/kg", "mosm/kg H2O"}},
        {"ms", {"MS", "ms"}},
        {"mL/min/kg", {"mL/(min·kg)", "mL/(min.kg)", "mL/kg/min", "ml/min/kg", "mL·min-1·kg-1"}},
        {"ng/g", {"ng/g creatinine"}},
        {"ng/mL", {"ng/ml", "ng/mL", "NG/ML"}},
        {"nkat/L", {"nkatal/L"}},
        {"nmol/L", {"nmol/l", "纳摩尔", "奈摩爾"}},
        {"pg/mL", {"pg/ml", "pg/mL", "PG/ML"}},
        {"pmol/L", {"pmol/l", "皮摩尔", "皮摩爾"}},
        {"ug/L", {"ug/l", "ug/L", "mcg/L", "mcg/l"}},
        {"ug/d", {"ug/24h", "ug/day"}},
        {"ug/dL", {"ug/dl", "mcg/dL", "mcg/dl"}},
        {"ug/g", {"ug/g creatinine", "ug/g creat"}},
        {"ug/mL", {"mcg/mL"}},
        {"ukat/L", {"ukatal/L"}},
        {"umol/L", {"umol/l", "微摩尔", "微摩爾"}},
        {"umol/dL", {"umol/dl"}},
    };
    return t;
}

}}}  // namespace mirobody::fhir::units
