#include "client/gcp_auth.hpp"

#include "client/http_client.hpp"
#include "platform/log.hpp"
#include "storage/sign.hpp"   // base64url_encode

#include <openssl/evp.h>
#include <openssl/pem.h>

#include <rapidjson/document.h>

#include <algorithm>
#include <cctype>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <fstream>
#include <functional>
#include <utility>
#include <memory>
#include <mutex>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>

#ifndef _WIN32
#include <pwd.h>
#include <unistd.h>
#endif

namespace mirobody { namespace gcp {

namespace {

// Google's token endpoint, and the grant the RFC 7523 assertion flow names. A
// service-account key carries its own token_uri (these are the values it holds
// in practice); the authorized-user flow has no such field and uses this.
const char* const kTokenUri = "https://oauth2.googleapis.com/token";
const char* const kJwtBearerGrant = "urn:ietf:params:oauth:grant-type:jwt-bearer";

// Google's STS endpoint. An external-account file generated by gcloud names its
// own token_url; external_account.py falls back to this when the field is
// absent, so a hand-written file that omits it still works.
const char* const kStsTokenUrl = "https://sts.googleapis.com/v1/token";

// The instance metadata server. The Metadata-Flavor header is required and is
// what makes the request un-forgeable by a browser (it cannot be sent
// cross-origin), so Google treats its presence as proof the caller is local.
const char* const kMetadataPath =
    "/computeMetadata/v1/instance/service-accounts/default/token";

// The name GCE publishes, and the link-local address it resolves to.
//
// Both, because the name is the part that breaks: it is served by the metadata
// DNS the VM is configured with, which a container does not inherit -- so on a
// GCE VM the address answers while the name does not resolve, and a deployment
// that IS on GCP looks exactly like one that is not. Google's own libraries do
// the same thing, and read the same GCE_METADATA_HOST override.
const char* const kMetadataHost = "metadata.google.internal";
const char* const kMetadataAddr = "169.254.169.254";

// Mint a new token this many seconds before the current one expires, so a token
// cannot lapse mid-request.
const std::int64_t kExpirySkew = 60;

// After a failed mint, wait this long before trying again. Without it, a
// deployment with no credentials at all (the metadata host does not resolve)
// pays the connect timeout on every single turn.
const std::int64_t kRetryBackoff = 30;

// The metadata server is on the local link; a slow answer means it is not there.
const int kMetadataTimeoutMs = 2000;
const int kTokenEndpointTimeoutMs = 10000;

std::int64_t now_secs() { return static_cast<std::int64_t>(std::time(nullptr)); }

std::string env_str(const char* name) {
    const char* v = std::getenv(name);
    return v ? std::string(v) : std::string();
}

std::string read_file(const std::string& path) {
    std::ifstream in(path.c_str(), std::ios::binary);
    if (!in) return std::string();
    std::ostringstream ss;
    ss << in.rdbuf();
    return ss.str();
}

// The gcloud configuration directory, resolved the way google.auth's
// _cloud_sdk.get_config_path() resolves it: CLOUDSDK_CONFIG wins outright, then
// the per-platform default.
//
// The fallbacks when HOME / APPDATA is unset are not padding. A server started
// by systemd, or by a container runtime with no user environment, frequently has
// no HOME at all -- and Python's expanduser("~") quietly reads the passwd entry
// in that case, so gcloud and the Python stack still find the file. Giving up
// here instead is how a host that DOES have an ADC file comes to look exactly
// like one that does not.
std::string gcloud_config_dir() {
    const std::string override_dir = env_str("CLOUDSDK_CONFIG");
    if (!override_dir.empty()) return override_dir;

#ifdef _WIN32
    const std::string appdata = env_str("APPDATA");
    if (!appdata.empty()) return appdata + "\\gcloud";
    const std::string drive = env_str("SystemDrive");
    return (drive.empty() ? std::string("C:") : drive) + "\\gcloud";
#else
    std::string home = env_str("HOME");
    if (home.empty()) {
        const struct passwd* pw = getpwuid(getuid());
        if (pw != nullptr && pw->pw_dir != nullptr) home = pw->pw_dir;
    }
    if (home.empty()) return std::string();
    return home + "/.config/gcloud";
#endif
}

// Where `gcloud auth application-default login` writes its credentials -- the
// path google.auth checks when GOOGLE_APPLICATION_CREDENTIALS is unset.
std::string well_known_adc_path() {
    const std::string dir = gcloud_config_dir();
    if (dir.empty()) return std::string();
#ifdef _WIN32
    return dir + "\\application_default_credentials.json";
#else
    return dir + "/application_default_credentials.json";
#endif
}

// A string member, or "" when absent / not a string.
std::string member_str(const rapidjson::Value& v, const char* key) {
    rapidjson::Value::ConstMemberIterator it = v.FindMember(key);
    if (it != v.MemberEnd() && it->value.IsString()) {
        return std::string(it->value.GetString(), it->value.GetStringLength());
    }
    return std::string();
}

// A string member of a nested object, or "" when either is absent.
std::string member_str_in(const rapidjson::Value& v, const char* obj, const char* key) {
    rapidjson::Value::ConstMemberIterator it = v.FindMember(obj);
    if (it == v.MemberEnd() || !it->value.IsObject()) return std::string();
    return member_str(it->value, key);
}

// Percent-encode a form value. The JWT assertion is base64url (nothing to
// escape), but a refresh token or client secret can carry anything.
std::string form_encode(const std::string& s) {
    static const char* kHex = "0123456789ABCDEF";
    std::string out;
    out.reserve(s.size());
    for (std::size_t i = 0; i < s.size(); ++i) {
        const unsigned char c = static_cast<unsigned char>(s[i]);
        if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') ||
            c == '-' || c == '_' || c == '.' || c == '~') {
            out.push_back(static_cast<char>(c));
        } else {
            out.push_back('%');
            out.push_back(kHex[c >> 4]);
            out.push_back(kHex[c & 0x0F]);
        }
    }
    return out;
}

// RSASSA-PKCS1-v1_5 over SHA-256 -- the JWT `RS256` signature. `pem` is the
// service-account key's private half (PKCS#8, as the JSON carries it). Returns
// the raw signature bytes, or "" if the key will not load or signing fails.
std::string rs256_sign(const std::string& pem, const std::string& input) {
    BIO* bio = BIO_new_mem_buf(pem.data(), static_cast<int>(pem.size()));
    if (!bio) return std::string();
    EVP_PKEY* key = PEM_read_bio_PrivateKey(bio, nullptr, nullptr, nullptr);
    BIO_free(bio);
    if (!key) return std::string();

    std::string sig;
    EVP_MD_CTX* ctx = EVP_MD_CTX_new();
    if (ctx != nullptr &&
        EVP_DigestSignInit(ctx, nullptr, EVP_sha256(), nullptr, key) == 1 &&
        EVP_DigestSignUpdate(ctx, input.data(), input.size()) == 1) {
        std::size_t n = 0;
        if (EVP_DigestSignFinal(ctx, nullptr, &n) == 1 && n > 0) {
            sig.resize(n);
            if (EVP_DigestSignFinal(ctx, reinterpret_cast<unsigned char*>(&sig[0]), &n) == 1) {
                sig.resize(n);
            } else {
                sig.clear();
            }
        }
    }
    if (ctx != nullptr) EVP_MD_CTX_free(ctx);
    EVP_PKEY_free(key);
    return sig;
}

// A short, safe snippet of an error body for logging.
std::string snippet(const std::string& s) {
    return s.size() > 200 ? s.substr(0, 200) + "..." : s;
}

}   // namespace

//------------------------------------------------------------------------------

const char* source_name(CredentialSource s) {
    switch (s) {
        case CredentialSource::ServiceAccount: return "service account";
        case CredentialSource::AuthorizedUser:  return "authorized user";
        case CredentialSource::ExternalAccount: return "workload identity federation";
        case CredentialSource::Metadata:       return "metadata server";
        default:                               return "none";
    }
}

AccessTokens::AccessTokens(std::string scope) : scope_(std::move(scope)) {}

//------------------------------------------------------------------------------

void AccessTokens::resolve() {
    resolved_ = true;

    // A JSON key, named explicitly or found where gcloud leaves it. Both files
    // have the same shape; `type` says which grant to run.
    const std::string named = env_str("GOOGLE_APPLICATION_CREDENTIALS");
    const std::string path  = named.empty() ? well_known_adc_path() : named;

    if (path.empty()) {
        platform::log_warn("gcp auth: nothing to read -- GOOGLE_APPLICATION_CREDENTIALS is "
                           "not set in this process's environment, and the gcloud config "
                           "directory could not be located either (no CLOUDSDK_CONFIG, no "
                           "HOME, no passwd entry). Asking the metadata server instead.");
    } else {
        const std::string raw = read_file(path);
        if (raw.empty()) {
            // Logged either way, and this is the point: a deployment that meant
            // to authenticate from a credential file and simply never got the
            // variable into the server's environment is otherwise
            // indistinguishable, in this log, from one correctly running on GCP
            // with nothing configured. The difference is the whole diagnosis, and
            // leaving the reader to guess at it is what this line exists for.
            if (!named.empty()) {
                platform::log_warn("gcp auth: GOOGLE_APPLICATION_CREDENTIALS='%s' cannot be "
                                   "read (missing, or not readable by this process's user). "
                                   "Asking the metadata server instead.", path.c_str());
            } else {
                platform::log_info("gcp auth: GOOGLE_APPLICATION_CREDENTIALS is not set in "
                                   "this process's environment and '%s' does not exist, so "
                                   "credentials will be asked of the metadata server. That "
                                   "is correct ON GCP and cannot work anywhere else -- off "
                                   "GCP, point that variable at a service-account key or at "
                                   "the external_account file a workload identity federation "
                                   "setup produces. It is read from the ENVIRONMENT only, "
                                   "the way google.auth reads it; a value in config.yml has "
                                   "no effect.", path.c_str());
            }
        } else {
            rapidjson::Document d;
            if (d.Parse(raw.c_str()).HasParseError() || !d.IsObject()) {
                platform::log_warn("gcp auth: credential file '%s' is not JSON", path.c_str());
            } else {
                const std::string type = member_str(d, "type");
                if (type == "service_account") {
                    sa_client_email_ = member_str(d, "client_email");
                    sa_private_key_  = member_str(d, "private_key");
                    sa_token_uri_    = member_str(d, "token_uri");
                    if (sa_token_uri_.empty()) sa_token_uri_ = kTokenUri;
                    if (!sa_client_email_.empty() && !sa_private_key_.empty()) {
                        source_ = CredentialSource::ServiceAccount;
                        platform::log_info("gcp auth: service-account credentials for %s (%s)",
                                           sa_client_email_.c_str(), path.c_str());
                        return;
                    }
                    platform::log_warn("gcp auth: service-account file '%s' lacks "
                                       "client_email / private_key", path.c_str());
                } else if (type == "authorized_user") {
                    au_client_id_     = member_str(d, "client_id");
                    au_client_secret_ = member_str(d, "client_secret");
                    au_refresh_token_ = member_str(d, "refresh_token");
                    if (!au_client_id_.empty() && !au_refresh_token_.empty()) {
                        source_ = CredentialSource::AuthorizedUser;
                        platform::log_info("gcp auth: authorized-user credentials (%s)",
                                           path.c_str());
                        return;
                    }
                    platform::log_warn("gcp auth: authorized-user file '%s' lacks "
                                       "client_id / refresh_token", path.c_str());
                } else if (type == "external_account") {
                    // Workload identity federation: no key here, only what is
                    // needed to prove this workload's own identity elsewhere.
                    ea_audience_           = member_str(d, "audience");
                    ea_subject_token_type_ = member_str(d, "subject_token_type");
                    ea_token_url_          = member_str(d, "token_url");
                    if (ea_token_url_.empty()) ea_token_url_ = kStsTokenUrl;
                    ea_impersonation_url_  = member_str(d, "service_account_impersonation_url");
                    ea_cs_file_            = member_str_in(d, "credential_source", "file");
                    ea_cs_url_             = member_str_in(d, "credential_source", "url");
                    ea_cs_environment_id_  = member_str_in(d, "credential_source", "environment_id");
                    ea_cs_region_url_      = member_str_in(d, "credential_source", "region_url");
                    ea_cs_security_creds_url_ = member_str_in(d, "credential_source", "url");
                    ea_cs_imdsv2_url_      = member_str_in(d, "credential_source",
                                                           "imdsv2_session_token_url");
                    ea_cs_regional_verification_url_ =
                        member_str_in(d, "credential_source", "regional_cred_verification_url");
                    // credential_source.format: {"type":"json","subject_token_field_name":...}
                    rapidjson::Value::ConstMemberIterator cs = d.FindMember("credential_source");
                    if (cs != d.MemberEnd() && cs->value.IsObject()) {
                        ea_cs_format_ = member_str_in(cs->value, "format", "type");
                        ea_cs_field_  = member_str_in(cs->value, "format",
                                                      "subject_token_field_name");
                        // credential_source.headers: sent with the GET when the
                        // token comes from a url (identity_pool.py) -- for an
                        // endpoint that wants a credential of its own before it
                        // will hand one out.
                        rapidjson::Value::ConstMemberIterator h = cs->value.FindMember("headers");
                        if (h != cs->value.MemberEnd() && h->value.IsObject()) {
                            for (rapidjson::Value::ConstMemberIterator m = h->value.MemberBegin();
                                 m != h->value.MemberEnd(); ++m) {
                                if (!m->value.IsString()) continue;
                                ea_cs_headers_.push_back(std::string(m->name.GetString()) + ": " +
                                                         m->value.GetString());
                            }
                        }
                    }
                    if (!ea_audience_.empty() && !ea_token_url_.empty()) {
                        source_ = CredentialSource::ExternalAccount;
                        platform::log_info("gcp auth: workload identity federation for %s "
                                           "(source: %s%s)",
                                           ea_audience_.c_str(),
                                           !ea_cs_file_.empty() ? "token file"
                                             : !ea_cs_environment_id_.empty() ? ea_cs_environment_id_.c_str()
                                             : !ea_cs_url_.empty() ? "token url" : "unknown",
                                           ea_impersonation_url_.empty() ? ""
                                                                         : ", impersonated");
                        return;
                    }
                    platform::log_warn("gcp auth: external-account file '%s' names no "
                                       "audience", path.c_str());
                } else {
                    // An absent `type` used to fall through in total silence,
                    // which is the same dead end as the file not being there at
                    // all but says nothing about which one happened.
                    const std::string what = type.empty()
                        ? std::string("no \"type\" field")
                        : ("an unsupported type '" + type + "'");
                    platform::log_warn("gcp auth: credential file '%s' has %s -- expected "
                                       "service_account, authorized_user or external_account",
                                       path.c_str(), what.c_str());
                }
            }
        }
    }

    // Nothing on disk: assume we are running on GCP and let the metadata server
    // answer. Whether it is actually there is decided by the first mint, not
    // here -- probing at resolve time would cost a round trip even for a process
    // that never calls Vertex.
    source_ = CredentialSource::Metadata;
}

//------------------------------------------------------------------------------

bool AccessTokens::accept_token_response(const std::string& body, const char* what) {
    rapidjson::Document d;
    if (d.Parse(body.c_str()).HasParseError() || !d.IsObject()) {
        platform::log_warn("gcp auth: %s returned a non-JSON body: %s",
                           what, snippet(body).c_str());
        return false;
    }
    const std::string tok = member_str(d, "access_token");
    if (tok.empty()) {
        platform::log_warn("gcp auth: %s returned no access_token: %s",
                           what, snippet(body).c_str());
        return false;
    }
    std::int64_t ttl = 3600;
    rapidjson::Value::ConstMemberIterator it = d.FindMember("expires_in");
    if (it != d.MemberEnd() && it->value.IsInt64()) ttl = it->value.GetInt64();
    if (ttl <= kExpirySkew) ttl = kExpirySkew + 1;   // never cache a token that is already stale

    token_      = tok;
    expires_at_ = now_secs() + ttl - kExpirySkew;
    return true;
}

bool AccessTokens::refresh_service_account() {
    // RFC 7523: a JWT signed by the key, exchanged for an access token.
    const std::int64_t iat = now_secs();
    const std::int64_t exp = iat + 3600;

    const std::string header = "{\"alg\":\"RS256\",\"typ\":\"JWT\"}";
    std::ostringstream claims;
    claims << "{\"iss\":\"" << sa_client_email_ << "\","
           << "\"scope\":\"" << scope_ << "\","
           << "\"aud\":\"" << sa_token_uri_ << "\","
           << "\"iat\":" << iat << ",\"exp\":" << exp << "}";

    const std::string signing_input = storage::base64url_encode(header) + "." +
                                      storage::base64url_encode(claims.str());
    const std::string sig = rs256_sign(sa_private_key_, signing_input);
    if (sig.empty()) {
        platform::log_error("gcp auth: could not sign the assertion (bad private_key?)");
        return false;
    }
    const std::string assertion = signing_input + "." + storage::base64url_encode(sig);

    client::HttpClient http;
    client::HttpRequest req;
    req.url          = sa_token_uri_;
    req.content_type = "application/x-www-form-urlencoded";
    req.body         = "grant_type=" + form_encode(kJwtBearerGrant) +
                       "&assertion=" + form_encode(assertion);
    req.request_timeout_ms = kTokenEndpointTimeoutMs;
    const client::HttpResponse resp = http.post(req);
    if (resp.status != 200) {
        platform::log_error("gcp auth: assertion exchange failed (HTTP %ld): %s",
                            resp.status, snippet(resp.body).c_str());
        return false;
    }
    return accept_token_response(resp.body, "the token endpoint");
}

bool AccessTokens::refresh_authorized_user() {
    client::HttpClient http;
    client::HttpRequest req;
    req.url          = kTokenUri;
    req.content_type = "application/x-www-form-urlencoded";
    req.body         = "grant_type=refresh_token"
                       "&client_id="     + form_encode(au_client_id_) +
                       "&client_secret=" + form_encode(au_client_secret_) +
                       "&refresh_token=" + form_encode(au_refresh_token_);
    req.request_timeout_ms = kTokenEndpointTimeoutMs;
    const client::HttpResponse resp = http.post(req);
    if (resp.status != 200) {
        platform::log_error("gcp auth: refresh_token grant failed (HTTP %ld): %s",
                            resp.status, snippet(resp.body).c_str());
        return false;
    }
    return accept_token_response(resp.body, "the token endpoint");
}

namespace {

// "2026-08-06T12:34:56Z" -> unix seconds, or 0 when it will not parse. The
// impersonation endpoint reports expiry this way rather than as a lifetime.
std::int64_t parse_rfc3339(const std::string& s) {
    int y = 0, mo = 0, d = 0, h = 0, mi = 0, sec = 0;
    if (std::sscanf(s.c_str(), "%d-%d-%dT%d:%d:%d", &y, &mo, &d, &h, &mi, &sec) != 6) return 0;
    std::tm tm = std::tm();
    tm.tm_year = y - 1900; tm.tm_mon = mo - 1; tm.tm_mday = d;
    tm.tm_hour = h; tm.tm_min = mi; tm.tm_sec = sec;
#ifdef _WIN32
    const std::time_t t = _mkgmtime(&tm);
#else
    const std::time_t t = timegm(&tm);
#endif
    return t == static_cast<std::time_t>(-1) ? 0 : static_cast<std::int64_t>(t);
}

}   // namespace

//------------------------------------------------------------------------------
// External account (workload identity federation)
//
// Ported from google-auth's external_account.py / identity_pool.py / aws.py /
// oauth2/sts.py, which is where this protocol actually lives -- the Python
// application code that works against it is one call to google.auth.default().
//------------------------------------------------------------------------------

namespace {

const char* const kStsGrantType     = "urn:ietf:params:oauth:grant-type:token-exchange";
const char* const kStsRequestedType = "urn:ietf:params:oauth:token-type:access_token";

// AWS SigV4 constants (aws.py). The signed request is never sent by us: Google
// replays it to AWS, which is what proves who the caller is.
const char* const kAwsAlgorithm   = "AWS4-HMAC-SHA256";
const char* const kAwsRequestType = "aws4_request";
const char* const kImdsv2Ttl      = "300";   // seconds; _IMDSV2_SESSION_TOKEN_TTL_SECONDS

// The default AWS caller-identity endpoint, when the credential file omits it.
const char* const kAwsDefaultVerificationUrl =
    "https://sts.{region}.amazonaws.com?Action=GetCallerIdentity&Version=2011-06-15";

std::string replace_all(std::string s, const std::string& from, const std::string& to) {
    for (std::size_t p = s.find(from); p != std::string::npos; p = s.find(from, p + to.size())) {
        s.replace(p, from.size(), to);
    }
    return s;
}

// The version in an "aws1"-style environment_id, or -1 when it is not that
// shape. aws.py matches /^(aws)([\d]+)$/ and supports version 1 only, so an
// "aws2" that someday exists is refused rather than signed the old way.
int aws_environment_version(const std::string& id) {
    if (id.size() <= 3 || id.compare(0, 3, "aws") != 0) return -1;
    int v = 0;
    for (std::size_t i = 3; i < id.size(); ++i) {
        if (id[i] < '0' || id[i] > '9') return -1;
        v = v * 10 + (id[i] - '0');
    }
    return v;
}

// The pieces of an https URL that SigV4 signs separately. `host` is what
// urlparse().hostname yields -- userinfo and :port stripped, lowercased --
// because that is both what aws.py signs and what it sends as the Host header,
// and the two have to agree for AWS to accept the replayed request. False for
// anything that is not https with a host, which aws.py rejects outright.
bool split_url(const std::string& url, std::string& host, std::string& path, std::string& query) {
    if (url.compare(0, 8, "https://") != 0) return false;
    const std::string rest = url.substr(8);
    const std::size_t slash = rest.find('/');
    const std::size_t qmark = rest.find('?');
    std::string authority = rest.substr(0, std::min(slash, qmark));
    if (qmark != std::string::npos) {
        query = rest.substr(qmark + 1);
        path  = (slash != std::string::npos && slash < qmark) ? rest.substr(slash, qmark - slash)
                                                             : std::string();
    } else {
        query.clear();
        path = (slash != std::string::npos) ? rest.substr(slash) : std::string();
    }

    const std::size_t at = authority.rfind('@');
    if (at != std::string::npos) authority = authority.substr(at + 1);
    const std::size_t colon = authority.rfind(':');
    // A ':' after the last ']' is a port; one inside brackets belongs to an IPv6
    // literal.
    if (colon != std::string::npos && authority.find(']', colon) == std::string::npos) {
        authority = authority.substr(0, colon);
    }
    for (std::size_t i = 0; i < authority.size(); ++i) {
        authority[i] = static_cast<char>(std::tolower(static_cast<unsigned char>(authority[i])));
    }
    host = authority;
    return !host.empty();
}

// posixpath.normpath over the URL path, which is how aws.py derives the
// canonical URI: duplicate slashes collapse, "." segments vanish, ".." resolves
// against what precedes it, a trailing slash is dropped. An empty path becomes
// "/" -- aws.py gets there by urljoin()ing normpath("")'s "." back onto the URL.
std::string canonical_path(const std::string& path) {
    std::vector<std::string> segments;
    std::size_t i = 0;
    while (i < path.size()) {
        std::size_t j = path.find('/', i);
        if (j == std::string::npos) j = path.size();
        const std::string segment = path.substr(i, j - i);
        if (segment == "..") {
            if (!segments.empty()) segments.pop_back();
        } else if (!segment.empty() && segment != ".") {
            segments.push_back(segment);
        }
        i = j + 1;
    }
    std::string out;
    for (std::size_t k = 0; k < segments.size(); ++k) { out += "/"; out += segments[k]; }
    return out.empty() ? std::string("/") : out;
}

int hex_value(char c) {
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
}

// Percent-decode with '+' meaning a space -- how urllib.parse.parse_qs reads a
// query string, and so the text aws.py re-encodes from.
std::string percent_decode(const std::string& s) {
    std::string out;
    out.reserve(s.size());
    for (std::size_t i = 0; i < s.size(); ++i) {
        if (s[i] == '+') { out.push_back(' '); continue; }
        if (s[i] == '%' && i + 2 < s.size()) {
            const int hi = hex_value(s[i + 1]), lo = hex_value(s[i + 2]);
            if (hi >= 0 && lo >= 0) {
                out.push_back(static_cast<char>(hi * 16 + lo));
                i += 2;
                continue;
            }
        }
        out.push_back(s[i]);
    }
    return out;
}

// The canonical query string SigV4 signs: every key and value decoded and then
// re-encoded down to the unreserved characters, pairs ordered by key and then by
// value. aws.py builds this with parse_qs + quote + sort rather than passing the
// raw query through, and the difference is a signature AWS rejects the moment a
// credential file names a regional_cred_verification_url whose parameters are in
// a different order or carry an escape.
//
// One deliberate difference: parse_qs drops a parameter whose value is empty,
// leaving it out of the signature while AWS still counts it. Blank parameters
// are kept here. The URL Google generates has none, so nothing changes for it.
std::string canonical_querystring(const std::string& query) {
    std::vector<std::pair<std::string, std::string> > pairs;
    std::size_t i = 0;
    while (i < query.size()) {
        std::size_t j = query.find('&', i);
        if (j == std::string::npos) j = query.size();
        const std::string field = query.substr(i, j - i);
        if (!field.empty()) {
            const std::size_t eq = field.find('=');
            const std::string key = (eq == std::string::npos) ? field : field.substr(0, eq);
            const std::string val = (eq == std::string::npos) ? std::string() : field.substr(eq + 1);
            pairs.push_back(std::make_pair(storage::uri_encode(percent_decode(key), true),
                                           storage::uri_encode(percent_decode(val), true)));
        }
        i = j + 1;
    }
    // Sorting the encoded pairs orders them by key and, within one key, by
    // value -- which is what aws.py's sort-the-values-then-sort-the-keys does.
    std::sort(pairs.begin(), pairs.end());
    std::string out;
    for (std::size_t k = 0; k < pairs.size(); ++k) {
        if (k) out += "&";
        out += pairs[k].first + "=" + pairs[k].second;
    }
    return out;
}

// The AWS service a host speaks for, from its first label: sts.us-east-1... is
// "sts", iam.amazonaws.com is "iam" (aws.py's host.split(".")[0]). It goes into
// both the credential scope and the signing-key derivation, so a hardcoded "sts"
// silently breaks any credential file naming a different endpoint.
std::string aws_service_from_host(const std::string& host) {
    const std::size_t dot = host.find('.');
    return dot == std::string::npos ? host : host.substr(0, dot);
}

// A JSON string with the few escapes these values can contain. The subject token
// is JSON that Google parses, so it has to be well formed even though every
// value here is a URL, a header name, or base64-ish signature text.
std::string json_quote(const std::string& s) {
    std::string out("\"");
    for (std::size_t i = 0; i < s.size(); ++i) {
        const char c = s[i];
        if (c == '"' || c == '\\') { out.push_back('\\'); out.push_back(c); }
        else if (c == '\n')        { out += "\\n"; }
        else if (c == '\r')        { out += "\\r"; }
        else if (c == '\t')        { out += "\\t"; }
        else                       { out.push_back(c); }
    }
    out.push_back('"');
    return out;
}

// IRSA / EKS Pod Identity: swap the projected web-identity token for temporary
// AWS credentials. `false` when the environment names no role, which is not an
// error -- it just means this is not a pod and the metadata server is next.
//
// This is the one piece google.auth.aws does not do for itself. Its built-in
// credential source reads EC2's instance metadata server and nothing else, and a
// pod usually cannot reach that at all: EKS requires IMDSv2 while leaving the
// metadata hop limit at 1, so the container's PUT for a session token is dropped
// on the way out while unauthenticated reads come back 401 -- a deadlock no
// credential file can configure around. What the pod does have is the token
// kubelet projects for it, and turning that into credentials is a single unsigned
// STS call: AssumeRoleWithWebIdentity carries no signature precisely because the
// token IS the credential, so there is no chicken-and-egg to break.
//
// google-auth's answer to this is AwsSecurityCredentialsSupplier, a hook the
// application implements -- which is exactly what the Python service in this
// stack does, delegating to boto3 (backend/utils/wif.py in theta-smart). Doing it
// in here instead means one credential file and one set of environment variables
// serve both, rather than each service needing its own arrangement.
//
// Not cached: a GCP token is minted about once an hour and this runs once per
// mint, so the assumed credentials are used immediately and thrown away. boto3
// caches because it signs many AWS requests; there is only ever one here.
bool aws_web_identity_credentials(client::HttpClient& http, const std::string& region,
                                  std::string& key_id, std::string& secret,
                                  std::string& session) {
    const std::string role_arn   = env_str("AWS_ROLE_ARN");
    const std::string token_file = env_str("AWS_WEB_IDENTITY_TOKEN_FILE");
    if (role_arn.empty() || token_file.empty()) return false;

    const std::string token = read_token_file(token_file);
    if (token.empty()) {
        platform::log_warn("gcp auth: workload identity (aws): AWS_ROLE_ARN names %s but the "
                           "web-identity token at '%s' is missing or empty -- is the service "
                           "account's projected token volume mounted?",
                           role_arn.c_str(), token_file.c_str());
        return false;
    }

    // Any string is a valid session name; botocore reads the same variable and
    // invents one when it is unset.
    std::string session_name = env_str("AWS_ROLE_SESSION_NAME");
    if (session_name.empty()) session_name = "mirobody";

    client::HttpRequest req;
    req.url          = "https://sts." + region + ".amazonaws.com/";
    req.content_type = "application/x-www-form-urlencoded";
    req.body         = "Action=AssumeRoleWithWebIdentity"
                       "&Version=2011-06-15"
                       "&RoleArn=" + form_encode(role_arn) +
                       "&RoleSessionName=" + form_encode(session_name) +
                       "&WebIdentityToken=" + form_encode(token);
    req.request_timeout_ms = kTokenEndpointTimeoutMs;
    const client::HttpResponse resp = http.post(req);
    if (resp.status != 200) {
        platform::log_error("gcp auth: workload identity (aws): AssumeRoleWithWebIdentity for "
                            "%s failed (HTTP %ld): %s. Check that the role's trust policy "
                            "accepts this cluster's OIDC provider and this service account.",
                            role_arn.c_str(), resp.status, snippet(resp.body).c_str());
        return false;
    }

    // STS answers in XML. A flat tag scan is enough -- each of these appears
    // exactly once, inside the single <Credentials> element.
    key_id  = storage::xml_tag_value(resp.body, "AccessKeyId");
    secret  = storage::xml_tag_value(resp.body, "SecretAccessKey");
    session = storage::xml_tag_value(resp.body, "SessionToken");
    if (key_id.empty() || secret.empty() || session.empty()) {
        platform::log_error("gcp auth: workload identity (aws): AssumeRoleWithWebIdentity "
                            "returned no usable credentials: %s", snippet(resp.body).c_str());
        key_id.clear();
        secret.clear();
        session.clear();
        return false;
    }
    platform::log_info("gcp auth: workload identity (aws): assumed %s with the projected "
                       "web-identity token (expires %s)", role_arn.c_str(),
                       storage::xml_tag_value(resp.body, "Expiration").c_str());
    return true;
}

}   // namespace

std::string AccessTokens::aws_subject_token() {
    client::HttpClient http;

    // The IMDSv2 session token, fetched at most once and only when something
    // actually has to be read from the metadata server. aws.py asks for it
    // separately inside each of its two metadata lookups, and in both cases only
    // after the environment failed to answer -- which is what lets this work on
    // Lambda, where the credentials arrive as environment variables and there is
    // no metadata server to reach at all. A host that supplies both the region
    // and the credentials that way never touches IMDS, and never pays its
    // connect timeout.
    bool imds_resolved = false;
    bool imds_usable   = true;
    std::vector<std::string> imds_headers;
    const std::function<bool()> imds = [&]() -> bool {
        if (imds_resolved) return imds_usable;
        imds_resolved = true;
        if (ea_cs_imdsv2_url_.empty()) return true;   // an IMDSv1 host names no url

        client::HttpRequest req;
        req.url = ea_cs_imdsv2_url_;
        req.headers.push_back(std::string("X-aws-ec2-metadata-token-ttl-seconds: ") + kImdsv2Ttl);
        req.request_timeout_ms = kMetadataTimeoutMs;
        const client::HttpResponse resp = http.request("PUT", req);
        if (resp.status == 200 && !resp.body.empty()) {
            imds_headers.push_back("X-aws-ec2-metadata-token: " + resp.body);
            return true;
        }
        // A configured imdsv2_session_token_url that will not answer means IMDSv1
        // is disabled on this instance, so every later read would come back 401.
        // Name the cause once here instead of leaving two unexplained 401s below.
        platform::log_warn("gcp auth: workload identity (aws): the IMDSv2 session token "
                           "request to %s failed (HTTP %ld); the instance metadata server "
                           "cannot be read without it",
                           ea_cs_imdsv2_url_.c_str(), resp.status);
        imds_usable = false;
        return false;
    };

    // 1. Region: the environment first, else the metadata region_url, whose
    //    answer is an availability zone -- the region is that minus its last
    //    character (aws.py::get_aws_region).
    std::string region = env_str("AWS_REGION");
    if (region.empty()) region = env_str("AWS_DEFAULT_REGION");
    if (region.empty()) {
        if (ea_cs_region_url_.empty()) {
            platform::log_warn("gcp auth: workload identity (aws): no region -- set AWS_REGION, "
                               "or give the credential file a region_url. In a pod the IRSA "
                               "webhook normally injects AWS_REGION for you, so its absence "
                               "suggests the pod is not annotated for a role.");
            return std::string();
        }
        if (!imds()) return std::string();
        const client::HttpResponse resp =
            http.get(ea_cs_region_url_, kMetadataTimeoutMs, imds_headers);
        if (resp.status != 200 || resp.body.size() < 2) {
            platform::log_warn("gcp auth: workload identity (aws): no region at %s (HTTP %ld)",
                               ea_cs_region_url_.c_str(), resp.status);
            return std::string();
        }
        region = resp.body.substr(0, resp.body.size() - 1);   // "us-east-1a" -> "us-east-1"
    }

    // 2. Security credentials, in the order the places they can come from stop
    //    being ambiguous:
    //
    //      a. the environment, but only when it carries BOTH halves -- aws.py does
    //         not mix a key id from there with a secret from elsewhere, and a
    //         half-set environment is far likelier a mistake than an intent.
    //      b. IRSA, when the environment names a role and a projected token. This
    //         goes ahead of the metadata server because in a pod it is the only
    //         one of the two that can work: the projected token is the identity
    //         that actually exists there, and IMDS is normally unreachable.
    //      c. the metadata server -- the EC2 instance profile.
    std::string key_id  = env_str("AWS_ACCESS_KEY_ID");
    std::string secret  = env_str("AWS_SECRET_ACCESS_KEY");
    std::string session = env_str("AWS_SESSION_TOKEN");
    if (key_id.empty() || secret.empty()) {
        key_id.clear();
        secret.clear();
        session.clear();
    }
    if (key_id.empty() &&
        !aws_web_identity_credentials(http, region, key_id, secret, session)) {
        if (ea_cs_security_creds_url_.empty()) {
            platform::log_warn("gcp auth: workload identity (aws): no AWS credentials -- the "
                               "environment names neither a key pair nor an IRSA role "
                               "(AWS_ROLE_ARN + AWS_WEB_IDENTITY_TOKEN_FILE), and the "
                               "credential file has no security-credentials url");
            return std::string();
        }
        if (!imds()) return std::string();
        const client::HttpResponse role =
            http.get(ea_cs_security_creds_url_, kMetadataTimeoutMs, imds_headers);
        if (role.status != 200 || role.body.empty()) {
            platform::log_warn("gcp auth: workload identity (aws): no role at %s (HTTP %ld). "
                               "On EC2, check that an instance profile is attached. In a pod "
                               "this endpoint is normally unreachable and the answer is IRSA "
                               "-- annotate the service account with "
                               "eks.amazonaws.com/role-arn so AWS_ROLE_ARN and "
                               "AWS_WEB_IDENTITY_TOKEN_FILE reach this process. On ECS or "
                               "Fargate the task role is served at another address entirely; "
                               "set AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY / "
                               "AWS_SESSION_TOKEN there.",
                               ea_cs_security_creds_url_.c_str(), role.status);
            return std::string();
        }
        const client::HttpResponse cred = http.get(
            ea_cs_security_creds_url_ + "/" + role.body, kMetadataTimeoutMs, imds_headers);
        if (cred.status != 200) {
            platform::log_warn("gcp auth: workload identity (aws): no credentials for role "
                               "'%s' (HTTP %ld)", role.body.c_str(), cred.status);
            return std::string();
        }
        rapidjson::Document d;
        if (d.Parse(cred.body.c_str()).HasParseError() || !d.IsObject()) {
            platform::log_warn("gcp auth: workload identity (aws): role credentials are not JSON");
            return std::string();
        }
        key_id  = member_str(d, "AccessKeyId");
        secret  = member_str(d, "SecretAccessKey");
        session = member_str(d, "Token");
        if (key_id.empty() || secret.empty()) {
            platform::log_warn("gcp auth: workload identity (aws): the metadata server's "
                               "credentials for role '%s' lack AccessKeyId / SecretAccessKey",
                               role.body.c_str());
            return std::string();
        }
    }

    // 3. Sign a GetCallerIdentity request for the region's STS endpoint. The
    //    request is never sent from here -- it IS the subject token.
    return aws_signed_request(
        ea_cs_regional_verification_url_.empty() ? kAwsDefaultVerificationUrl
                                                 : ea_cs_regional_verification_url_,
        region, key_id, secret, session, ea_audience_, std::time(nullptr));
}

//------------------------------------------------------------------------------

std::string aws_signed_request(const std::string& verification_url,
                               const std::string& region,
                               const std::string& access_key_id,
                               const std::string& secret_access_key,
                               const std::string& session_token,
                               const std::string& audience,
                               std::time_t now) {
    const std::string url = replace_all(verification_url, "{region}", region);
    std::string host, raw_path, raw_query;
    if (!split_url(url, host, raw_path, raw_query)) {
        platform::log_warn("gcp auth: workload identity (aws): '%s' is not a valid https "
                           "service URL", url.c_str());
        return std::string();
    }
    const std::string canonical_uri   = canonical_path(raw_path);
    const std::string canonical_query = canonical_querystring(raw_query);
    const std::string service         = aws_service_from_host(host);

    std::tm tm = std::tm();
#ifdef _WIN32
    gmtime_s(&tm, &now);
#else
    gmtime_r(&now, &tm);
#endif
    char amz_date[32] = {0}, date_stamp[16] = {0};
    std::strftime(amz_date, sizeof(amz_date), "%Y%m%dT%H%M%SZ", &tm);
    std::strftime(date_stamp, sizeof(date_stamp), "%Y%m%d", &tm);

    // Canonical headers, sorted by name (aws.py sorts the map's keys).
    std::vector<std::pair<std::string, std::string> > hdrs;
    hdrs.push_back(std::make_pair("host", host));
    hdrs.push_back(std::make_pair("x-amz-date", std::string(amz_date)));
    if (!session_token.empty()) {
        hdrs.push_back(std::make_pair("x-amz-security-token", session_token));
    }
    std::sort(hdrs.begin(), hdrs.end());

    std::string canonical_headers, signed_headers;
    for (std::size_t i = 0; i < hdrs.size(); ++i) {
        canonical_headers += hdrs[i].first + ":" + hdrs[i].second + "\n";
        if (i) signed_headers += ";";
        signed_headers += hdrs[i].first;
    }

    const std::string payload_hash = storage::sha256_hex("");
    const std::string canonical_request = std::string("POST") + "\n" + canonical_uri + "\n" +
                                          canonical_query + "\n" + canonical_headers + "\n" +
                                          signed_headers + "\n" + payload_hash;
    const std::string scope = std::string(date_stamp) + "/" + region + "/" + service + "/" +
                              kAwsRequestType;
    const std::string string_to_sign = std::string(kAwsAlgorithm) + "\n" + amz_date + "\n" +
                                       scope + "\n" + storage::sha256_hex(canonical_request);
    const std::string signature = storage::aws_sigv4_signature(secret_access_key, date_stamp,
                                                               region, service, string_to_sign);
    const std::string authorization = std::string(kAwsAlgorithm) + " Credential=" +
                                      access_key_id + "/" + scope +
                                      ", SignedHeaders=" + signed_headers +
                                      ", Signature=" + signature;

    // Serialize as Google expects: {url, method, headers:[{key,value}...]}, keys
    // sorted, no spaces, then percent-encoded (Python's quote(), which leaves '/'
    // alone). The header order below is the order aws.py inserts them in, and the
    // three object keys are already in the order json.dumps(sort_keys=True) emits.
    std::vector<std::pair<std::string, std::string> > out_hdrs;
    out_hdrs.push_back(std::make_pair("Authorization", authorization));
    out_hdrs.push_back(std::make_pair("host", host));
    out_hdrs.push_back(std::make_pair("x-amz-date", std::string(amz_date)));
    if (!session_token.empty()) {
        out_hdrs.push_back(std::make_pair("x-amz-security-token", session_token));
    }
    // Added AFTER signing, exactly as aws.py does -- it travels with the request
    // but is not covered by the signature.
    out_hdrs.push_back(std::make_pair("x-goog-cloud-target-resource", audience));

    std::string json = "{\"headers\":[";
    for (std::size_t i = 0; i < out_hdrs.size(); ++i) {
        if (i) json += ",";
        json += "{\"key\":" + json_quote(out_hdrs[i].first) +
                ",\"value\":" + json_quote(out_hdrs[i].second) + "}";
    }
    json += "],\"method\":\"POST\",\"url\":" + json_quote(url) + "}";
    return storage::uri_encode(json, false);
}

std::string AccessTokens::subject_token() {
    // environment_id FIRST, the way google-auth picks its credential class. The
    // aws1 source also carries a `url` -- the security-credentials endpoint --
    // so testing `url` first would read AWS's role listing as if it were the
    // token itself.
    if (!ea_cs_environment_id_.empty()) {
        if (aws_environment_version(ea_cs_environment_id_) == 1) return aws_subject_token();
        platform::log_warn("gcp auth: workload identity: unsupported credential_source "
                           "(environment_id='%s'; only 'aws1' is supported)",
                           ea_cs_environment_id_.c_str());
        return std::string();
    }

    // A file or a URL: the token is read, not built. This is the shape a
    // Kubernetes projected service-account token takes.
    std::string raw;
    if (!ea_cs_file_.empty()) {
        raw = read_file(ea_cs_file_);
        if (raw.empty()) {
            platform::log_warn("gcp auth: workload identity: token file '%s' is missing or empty",
                               ea_cs_file_.c_str());
            return std::string();
        }
    } else if (!ea_cs_url_.empty()) {
        client::HttpClient http;
        const client::HttpResponse resp =
            http.get(ea_cs_url_, kTokenEndpointTimeoutMs, ea_cs_headers_);
        if (resp.status != 200) {
            platform::log_warn("gcp auth: workload identity: token url '%s' answered HTTP %ld",
                               ea_cs_url_.c_str(), resp.status);
            return std::string();
        }
        raw = resp.body;
    } else if (!env_str("AWS_ROLE_ARN").empty() &&
               !env_str("AWS_WEB_IDENTITY_TOKEN_FILE").empty()) {
        // No credential_source at all, but the environment names an IRSA role.
        // Accepted because that is the shape google-auth's programmatic supplier
        // takes -- a caller passing credential_source=None and supplying the AWS
        // credentials itself, which is what the Python service in this stack does.
        // Taking it here too means one credential file is valid input to both,
        // whether or not whoever generated it filled in a credential_source.
        return aws_subject_token();
    } else {
        platform::log_warn("gcp auth: workload identity: credential_source names neither a "
                           "file, a url, nor an environment_id, and the environment names no "
                           "IRSA role to stand in for one");
        return std::string();
    }

    if (ea_cs_format_ == "json") {
        rapidjson::Document d;
        if (d.Parse(raw.c_str()).HasParseError() || !d.IsObject()) {
            platform::log_warn("gcp auth: workload identity: token source is not JSON");
            return std::string();
        }
        return member_str(d, ea_cs_field_.c_str());
    }
    // "text": the content itself, minus the trailing newline a file tends to carry.
    const std::size_t end = raw.find_last_not_of(" \t\r\n");
    return end == std::string::npos ? std::string() : raw.substr(0, end + 1);
}

bool AccessTokens::refresh_external_account() {
    const std::string subject = subject_token();
    if (subject.empty()) return false;   // the source already said why

    // STS token exchange (oauth2/sts.py): form-encoded, empty fields omitted.
    client::HttpClient http;
    client::HttpRequest req;
    req.url          = ea_token_url_;
    req.content_type = "application/x-www-form-urlencoded";
    req.body = "grant_type=" + form_encode(kStsGrantType) +
               "&audience=" + form_encode(ea_audience_) +
               "&scope=" + form_encode(scope_) +
               "&requested_token_type=" + form_encode(kStsRequestedType) +
               "&subject_token=" + form_encode(subject) +
               "&subject_token_type=" + form_encode(ea_subject_token_type_);
    req.request_timeout_ms = kTokenEndpointTimeoutMs;
    const client::HttpResponse resp = http.post(req);
    if (resp.status != 200) {
        platform::log_error("gcp auth: workload identity: STS exchange failed (HTTP %ld): %s",
                            resp.status, snippet(resp.body).c_str());
        return false;
    }
    if (ea_impersonation_url_.empty()) {
        return accept_token_response(resp.body, "the STS token exchange");
    }

    // Impersonation: the federated token only authorizes borrowing the service
    // account, so swap it for that account's own token.
    rapidjson::Document fed;
    if (fed.Parse(resp.body.c_str()).HasParseError() || !fed.IsObject()) {
        platform::log_error("gcp auth: workload identity: STS returned a non-JSON body");
        return false;
    }
    const std::string federated = member_str(fed, "access_token");
    if (federated.empty()) {
        platform::log_error("gcp auth: workload identity: STS returned no access_token: %s",
                            snippet(resp.body).c_str());
        return false;
    }

    client::HttpRequest imp;
    imp.url  = ea_impersonation_url_;
    imp.body = "{\"scope\":[" + json_quote(scope_) + "]}";
    imp.headers.push_back("Authorization: Bearer " + federated);
    imp.request_timeout_ms = kTokenEndpointTimeoutMs;
    const client::HttpResponse ir = http.post(imp);
    if (ir.status != 200) {
        platform::log_error("gcp auth: workload identity: impersonation failed (HTTP %ld): %s",
                            ir.status, snippet(ir.body).c_str());
        return false;
    }
    rapidjson::Document d;
    if (d.Parse(ir.body.c_str()).HasParseError() || !d.IsObject()) {
        platform::log_error("gcp auth: workload identity: impersonation returned a non-JSON body");
        return false;
    }
    const std::string tok = member_str(d, "accessToken");
    if (tok.empty()) {
        platform::log_error("gcp auth: workload identity: impersonation returned no accessToken: %s",
                            snippet(ir.body).c_str());
        return false;
    }
    // expireTime is an RFC 3339 instant rather than a lifetime. An unparsable one
    // is treated as the shortest sane life rather than trusted forever.
    const std::int64_t exp = parse_rfc3339(member_str(d, "expireTime"));
    token_      = tok;
    expires_at_ = (exp > 0 ? exp : now_secs() + 3600) - kExpirySkew;
    return true;
}

bool AccessTokens::refresh_metadata() {
    // GCE_METADATA_HOST is Google's documented override (host or host:port) and
    // wins outright. Otherwise try the published name, then the link-local
    // address it stands for: inside a container the name usually does not
    // resolve even though the address answers, and giving up on the name would
    // leave a deployment that is on GCP unable to authenticate.
    std::vector<std::string> hosts;
    const std::string override_host = env_str("GCE_METADATA_HOST");
    if (!override_host.empty()) {
        hosts.push_back(override_host);
    } else {
        hosts.push_back(kMetadataHost);
        hosts.push_back(kMetadataAddr);
    }

    client::HttpClient http;
    std::vector<std::string> headers;
    headers.push_back("Metadata-Flavor: Google");

    for (std::size_t i = 0; i < hosts.size(); ++i) {
        const std::string url = "http://" + hosts[i] + kMetadataPath;
        const client::HttpResponse resp = http.get(url, kMetadataTimeoutMs, headers);

        // Whatever answered has to prove it is Google's. 169.254.169.254 is the
        // link-local metadata address EVERY cloud uses -- AWS, Azure, Alibaba --
        // so on another provider something does answer here, and believing it
        // would turn "you are not on GCP" into an unexplained auth failure.
        // Google's own libraries make the same check; the header cannot be sent
        // cross-origin by a browser, which is what it is for.
        std::unordered_map<std::string, std::string>::const_iterator flavor =
            resp.headers.find("metadata-flavor");
        const bool is_google = flavor != resp.headers.end() && flavor->second == "Google";

        if (resp.status == 200 && is_google) {
            if (i > 0) {
                // Worth saying: it means DNS is the broken part, not the
                // credentials, and the next reader of this log should not go
                // looking for a permissions problem.
                platform::log_info("gcp auth: metadata server reached at %s "
                                   "('%s' does not resolve here)",
                                   hosts[i].c_str(), kMetadataHost);
            }
            return accept_token_response(resp.body, "the metadata server");
        }

        // Something answered, but not Google. Naming that outright is the whole
        // point: no amount of GCP configuration will fix a host that is not on
        // GCP, and the reader needs to stop looking for one.
        if (resp.status > 0 && !is_google) {
            platform::log_warn(
                "gcp auth: %s answered HTTP %ld but is not Google's metadata server "
                "(no 'Metadata-Flavor: Google' in the response). That address is the "
                "link-local metadata endpoint every cloud uses, so this host is most "
                "likely NOT on GCP -- 401 there is AWS IMDSv2, for instance. "
                "Application default credentials cannot work here: set "
                "GOOGLE_APPLICATION_CREDENTIALS to a service-account key file, or "
                "GCP_ACCESS_TOKEN_FILE to a token the deployment keeps current.",
                hosts[i].c_str(), resp.status);
            return false;
        }

        // A transport failure (status <= 0) against one host says nothing about
        // the next; a real HTTP status from Google's own server does -- it is
        // there and refused, so stop and report that.
        if (resp.status > 0 || i + 1 == hosts.size()) {
            platform::log_warn("gcp auth: the metadata server did not answer at %s "
                               "(HTTP %ld): %s. On GCP, check that a service account is "
                               "attached to this instance; elsewhere set "
                               "GOOGLE_APPLICATION_CREDENTIALS to a service-account key, "
                               "or GCP_ACCESS_TOKEN_FILE to a token the deployment keeps "
                               "current.",
                               hosts[i].c_str(), resp.status, snippet(resp.body).c_str());
            return false;
        }
    }
    return false;
}

bool AccessTokens::refresh() {
    switch (source_) {
        case CredentialSource::ServiceAccount: return refresh_service_account();
        case CredentialSource::AuthorizedUser:  return refresh_authorized_user();
        case CredentialSource::ExternalAccount: return refresh_external_account();
        case CredentialSource::Metadata:        return refresh_metadata();
        default:                               return false;
    }
}

//------------------------------------------------------------------------------

std::string AccessTokens::token() {
    std::lock_guard<std::mutex> lk(mu_);

    const std::int64_t now = now_secs();
    if (!token_.empty() && now < expires_at_) return token_;   // still good
    if (now < retry_after_) return std::string();              // a recent mint failed

    if (!resolved_) resolve();

    if (refresh()) {
        retry_after_ = 0;
        return token_;
    }
    token_.clear();
    expires_at_ = 0;
    retry_after_ = now + kRetryBackoff;
    return std::string();
}

CredentialSource AccessTokens::source() {
    std::lock_guard<std::mutex> lk(mu_);
    return source_;
}

//------------------------------------------------------------------------------

std::string read_token_file(const std::string& path) {
    // Trimmed because a token file conventionally ends in a newline, which would
    // otherwise be sent inside the Authorization header.
    const std::string raw = read_file(path);
    const std::size_t b = raw.find_first_not_of(" \t\r\n");
    if (b == std::string::npos) return std::string();
    return raw.substr(b, raw.find_last_not_of(" \t\r\n") - b + 1);
}

std::string TokenSource::token() {
    std::lock_guard<std::mutex> lk(mu_);
    if (!token_file_.empty()) return read_token_file(token_file_);
    if (!inline_token_.empty()) return inline_token_;
    if (!adc_) adc_ = std::make_shared<AccessTokens>();
    return adc_->token();
}

const char* TokenSource::describe() const {
    if (!token_file_.empty())   return "file, re-read per request";
    if (!inline_token_.empty()) return "inline, fixed at startup";
    return "application default credentials";
}

//------------------------------------------------------------------------------

std::string vertex_host(const std::string& location, const char* scheme) {
    const std::string s = std::string(scheme) + "://";
    if (location.empty())     return std::string();
    if (location == "global") return s + "aiplatform.googleapis.com";
    // Newer Gemini models publish the multi-regions and nothing else, so this
    // branch is not an exotic case -- it is the one a data-residency deployment
    // lands on. Both are enumerated rather than pattern-matched: "us" and "eu"
    // are the only two, and a region like "us-central1" must not be caught here.
    if (location == "us" || location == "eu")
        return s + "aiplatform." + location + ".rep.googleapis.com";
    return s + location + "-aiplatform.googleapis.com";
}

std::string vertex_model_location(
    const std::unordered_map<std::string, std::string>& per_model,
    const std::string& model,
    const std::string& fallback) {
    std::unordered_map<std::string, std::string>::const_iterator it = per_model.find(model);
    // An empty override reads as unset, the rule every other config value
    // follows (ConfigStore::get_str), so blanking one entry in the map returns
    // that model to the shared location instead of building a hostless URL.
    if (it != per_model.end() && !it->second.empty()) return it->second;
    return fallback;
}

}}
